// AUTO-GENERATED by `pnpm setup brevo`: Brevo template IDs per notification event.
export const BREVO_TEMPLATES = {
  welcome: {
    id: 1,
    critical: false,
  },
  new_device_signin: {
    id: 2,
    critical: true,
  },
  otp_lockout: {
    id: 3,
    critical: true,
  },
  application_received: {
    id: 4,
    critical: false,
  },
  application_received_admin: {
    id: 5,
    critical: false,
  },
  application_approved: {
    id: 6,
    critical: true,
  },
  application_rejected: {
    id: 7,
    critical: true,
  },
  assignment_new: {
    id: 8,
    critical: false,
  },
  assignment_due_soon: {
    id: 9,
    critical: false,
  },
  assignment_overdue: {
    id: 10,
    critical: false,
  },
  group_announcement: {
    id: 11,
    critical: false,
  },
  join_request_pending: {
    id: 12,
    critical: false,
  },
  join_request_approved: {
    id: 13,
    critical: false,
  },
  report_ready: {
    id: 14,
    critical: false,
  },
  account_suspended: {
    id: 15,
    critical: true,
  },
  account_restored: {
    id: 16,
    critical: true,
  },
  account_deletion_requested: {
    id: 17,
    critical: true,
  },
  account_deletion_completed: {
    id: 18,
    critical: true,
  },
  admin_promoted: {
    id: 19,
    critical: true,
  },
  admin_demoted: {
    id: 20,
    critical: true,
  },
} as const;
