// AUTO-GENERATED by `pnpm db:types`. Do not edit by hand.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.18';
  };
  public: {
    Tables: {
      achievements: {
        Row: {
          created_at: string;
          description_en: string;
          description_fil: string;
          icon_key: string;
          id: string;
          key: string;
          name_en: string;
          name_fil: string;
          reward_items: string[];
          rule: Json;
          sort_order: number;
        };
        Insert: {
          created_at?: string;
          description_en: string;
          description_fil: string;
          icon_key?: string;
          id?: string;
          key: string;
          name_en: string;
          name_fil: string;
          reward_items?: string[];
          rule: Json;
          sort_order?: number;
        };
        Update: {
          created_at?: string;
          description_en?: string;
          description_fil?: string;
          icon_key?: string;
          id?: string;
          key?: string;
          name_en?: string;
          name_fil?: string;
          reward_items?: string[];
          rule?: Json;
          sort_order?: number;
        };
        Relationships: [];
      };
      announcements: {
        Row: {
          body: string;
          created_at: string;
          created_by: string;
          group_id: string | null;
          id: string;
          scope: string;
          title: string;
        };
        Insert: {
          body: string;
          created_at?: string;
          created_by?: string;
          group_id?: string | null;
          id?: string;
          scope: string;
          title: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          created_by?: string;
          group_id?: string | null;
          id?: string;
          scope?: string;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'announcements_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'announcements_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
        ];
      };
      assignments: {
        Row: {
          created_at: string;
          created_by: string;
          due_at: string;
          group_id: string;
          id: string;
          level_ids: number[];
          min_stars: number;
          reminded_due_soon: boolean;
          reminded_overdue: boolean;
          starts_at: string;
          title: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string;
          due_at: string;
          group_id: string;
          id?: string;
          level_ids: number[];
          min_stars?: number;
          reminded_due_soon?: boolean;
          reminded_overdue?: boolean;
          starts_at?: string;
          title: string;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          due_at?: string;
          group_id?: string;
          id?: string;
          level_ids?: number[];
          min_stars?: number;
          reminded_due_soon?: boolean;
          reminded_overdue?: boolean;
          starts_at?: string;
          title?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'assignments_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'assignments_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
        ];
      };
      attempt_events: {
        Row: {
          attempt_id: string;
          byte_size: number;
          created_at: string;
          events: Json;
        };
        Insert: {
          attempt_id: string;
          byte_size: number;
          created_at?: string;
          events: Json;
        };
        Update: {
          attempt_id?: string;
          byte_size?: number;
          created_at?: string;
          events?: Json;
        };
        Relationships: [
          {
            foreignKeyName: 'attempt_events_attempt_id_fkey';
            columns: ['attempt_id'];
            isOneToOne: true;
            referencedRelation: 'attempts';
            referencedColumns: ['id'];
          },
        ];
      };
      attempts: {
        Row: {
          assignment_id: string | null;
          daily_date: string | null;
          device_id: string | null;
          duration_ms: number | null;
          finished_at: string | null;
          flag_reasons: string[];
          hazard_hits: number | null;
          id: string;
          idempotency_key: string | null;
          imported: boolean;
          level_id: number;
          level_version_id: string;
          live_session_id: string | null;
          mode: string;
          npcs_rescued: number | null;
          score: number | null;
          seed: number;
          stars: number | null;
          started_at: string;
          status: string;
          summary: Json | null;
          user_id: string;
          void_reason: string | null;
          voided_by: string | null;
        };
        Insert: {
          assignment_id?: string | null;
          daily_date?: string | null;
          device_id?: string | null;
          duration_ms?: number | null;
          finished_at?: string | null;
          flag_reasons?: string[];
          hazard_hits?: number | null;
          id?: string;
          idempotency_key?: string | null;
          imported?: boolean;
          level_id: number;
          level_version_id: string;
          live_session_id?: string | null;
          mode?: string;
          npcs_rescued?: number | null;
          score?: number | null;
          seed: number;
          stars?: number | null;
          started_at?: string;
          status?: string;
          summary?: Json | null;
          user_id: string;
          void_reason?: string | null;
          voided_by?: string | null;
        };
        Update: {
          assignment_id?: string | null;
          daily_date?: string | null;
          device_id?: string | null;
          duration_ms?: number | null;
          finished_at?: string | null;
          flag_reasons?: string[];
          hazard_hits?: number | null;
          id?: string;
          idempotency_key?: string | null;
          imported?: boolean;
          level_id?: number;
          level_version_id?: string;
          live_session_id?: string | null;
          mode?: string;
          npcs_rescued?: number | null;
          score?: number | null;
          seed?: number;
          stars?: number | null;
          started_at?: string;
          status?: string;
          summary?: Json | null;
          user_id?: string;
          void_reason?: string | null;
          voided_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'attempts_assignment_id_fkey';
            columns: ['assignment_id'];
            isOneToOne: false;
            referencedRelation: 'assignments';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'attempts_level_id_fkey';
            columns: ['level_id'];
            isOneToOne: false;
            referencedRelation: 'levels';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'attempts_level_version_id_fkey';
            columns: ['level_version_id'];
            isOneToOne: false;
            referencedRelation: 'level_versions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'attempts_live_session_id_fkey';
            columns: ['live_session_id'];
            isOneToOne: false;
            referencedRelation: 'live_sessions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'attempts_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'attempts_voided_by_fkey';
            columns: ['voided_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      audit_logs: {
        Row: {
          action: string;
          actor_id: string | null;
          actor_role: string | null;
          created_at: string;
          id: number;
          ip: unknown;
          metadata: Json;
          target_id: string | null;
          target_type: string | null;
          user_agent: string | null;
        };
        Insert: {
          action: string;
          actor_id?: string | null;
          actor_role?: string | null;
          created_at?: string;
          id?: number;
          ip?: unknown;
          metadata?: Json;
          target_id?: string | null;
          target_type?: string | null;
          user_agent?: string | null;
        };
        Update: {
          action?: string;
          actor_id?: string | null;
          actor_role?: string | null;
          created_at?: string;
          id?: number;
          ip?: unknown;
          metadata?: Json;
          target_id?: string | null;
          target_type?: string | null;
          user_agent?: string | null;
        };
        Relationships: [];
      };
      cosmetic_items: {
        Row: {
          is_reward: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          slot: string;
          unlock_rule: Json;
        };
        Insert: {
          is_reward?: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          slot: string;
          unlock_rule: Json;
        };
        Update: {
          is_reward?: boolean;
          key?: string;
          name_en?: string;
          name_fil?: string;
          slot?: string;
          unlock_rule?: Json;
        };
        Relationships: [];
      };
      daily_challenges: {
        Row: {
          created_at: string;
          date: string;
          level_id: number;
          modifiers: Json;
          seed: number;
        };
        Insert: {
          created_at?: string;
          date: string;
          level_id: number;
          modifiers?: Json;
          seed: number;
        };
        Update: {
          created_at?: string;
          date?: string;
          level_id?: number;
          modifiers?: Json;
          seed?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'daily_challenges_level_id_fkey';
            columns: ['level_id'];
            isOneToOne: false;
            referencedRelation: 'levels';
            referencedColumns: ['id'];
          },
        ];
      };
      email_outbox: {
        Row: {
          attempts: number;
          created_at: string;
          id: string;
          last_error: string | null;
          locale: string;
          next_attempt_at: string;
          params: Json;
          provider_message_id: string | null;
          sent_at: string | null;
          status: string;
          template_key: string;
          to_email: string;
          user_id: string | null;
        };
        Insert: {
          attempts?: number;
          created_at?: string;
          id?: string;
          last_error?: string | null;
          locale?: string;
          next_attempt_at?: string;
          params?: Json;
          provider_message_id?: string | null;
          sent_at?: string | null;
          status?: string;
          template_key: string;
          to_email: string;
          user_id?: string | null;
        };
        Update: {
          attempts?: number;
          created_at?: string;
          id?: string;
          last_error?: string | null;
          locale?: string;
          next_attempt_at?: string;
          params?: Json;
          provider_message_id?: string | null;
          sent_at?: string | null;
          status?: string;
          template_key?: string;
          to_email?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'email_outbox_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      email_suppressions: {
        Row: {
          created_at: string;
          email: string;
          reason: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          reason: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          reason?: string;
        };
        Relationships: [];
      };
      facilitator_applications: {
        Row: {
          contact: string;
          created_at: string;
          full_name: string;
          id: string;
          organization: string;
          position: string;
          proof_path: string | null;
          reason: string;
          review_note: string | null;
          reviewed_at: string | null;
          reviewer_id: string | null;
          status: string;
          user_id: string;
        };
        Insert: {
          contact: string;
          created_at?: string;
          full_name: string;
          id?: string;
          organization: string;
          position: string;
          proof_path?: string | null;
          reason: string;
          review_note?: string | null;
          reviewed_at?: string | null;
          reviewer_id?: string | null;
          status?: string;
          user_id?: string;
        };
        Update: {
          contact?: string;
          created_at?: string;
          full_name?: string;
          id?: string;
          organization?: string;
          position?: string;
          proof_path?: string | null;
          reason?: string;
          review_note?: string | null;
          reviewed_at?: string | null;
          reviewer_id?: string | null;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'facilitator_applications_reviewer_id_fkey';
            columns: ['reviewer_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'facilitator_applications_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      gobag_items: {
        Row: {
          category: string;
          created_at: string;
          explanation_en: string;
          explanation_fil: string;
          id: string;
          is_essential: boolean;
          is_published: boolean;
          key: string;
          model_key: string | null;
          name_en: string;
          name_fil: string;
          points: number;
          sort_order: number;
          updated_at: string;
          weight_kg: number;
        };
        Insert: {
          category: string;
          created_at?: string;
          explanation_en: string;
          explanation_fil: string;
          id?: string;
          is_essential?: boolean;
          is_published?: boolean;
          key: string;
          model_key?: string | null;
          name_en: string;
          name_fil: string;
          points?: number;
          sort_order?: number;
          updated_at?: string;
          weight_kg: number;
        };
        Update: {
          category?: string;
          created_at?: string;
          explanation_en?: string;
          explanation_fil?: string;
          id?: string;
          is_essential?: boolean;
          is_published?: boolean;
          key?: string;
          model_key?: string | null;
          name_en?: string;
          name_fil?: string;
          points?: number;
          sort_order?: number;
          updated_at?: string;
          weight_kg?: number;
        };
        Relationships: [];
      };
      group_members: {
        Row: {
          decided_at: string | null;
          decided_by: string | null;
          group_id: string;
          joined_at: string;
          status: string;
          user_id: string;
        };
        Insert: {
          decided_at?: string | null;
          decided_by?: string | null;
          group_id: string;
          joined_at?: string;
          status: string;
          user_id: string;
        };
        Update: {
          decided_at?: string | null;
          decided_by?: string | null;
          group_id?: string;
          joined_at?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'group_members_decided_by_fkey';
            columns: ['decided_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      groups: {
        Row: {
          created_at: string;
          description: string | null;
          facilitator_id: string;
          id: string;
          is_archived: boolean;
          join_code: string;
          max_members: number;
          name: string;
          requires_approval: boolean;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          facilitator_id?: string;
          id?: string;
          is_archived?: boolean;
          join_code: string;
          max_members?: number;
          name: string;
          requires_approval?: boolean;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          facilitator_id?: string;
          id?: string;
          is_archived?: boolean;
          join_code?: string;
          max_members?: number;
          name?: string;
          requires_approval?: boolean;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'groups_facilitator_id_fkey';
            columns: ['facilitator_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      hazards: {
        Row: {
          created_at: string;
          explanation_en: string;
          explanation_fil: string;
          id: string;
          instant_fail: boolean;
          is_published: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          penalty: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          explanation_en: string;
          explanation_fil: string;
          id?: string;
          instant_fail?: boolean;
          is_published?: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          penalty?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          explanation_en?: string;
          explanation_fil?: string;
          id?: string;
          instant_fail?: boolean;
          is_published?: boolean;
          key?: string;
          name_en?: string;
          name_fil?: string;
          penalty?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      home_tasks: {
        Row: {
          created_at: string;
          explanation_en: string;
          explanation_fil: string;
          id: string;
          is_published: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          points: number;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          explanation_en: string;
          explanation_fil: string;
          id?: string;
          is_published?: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          points?: number;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          explanation_en?: string;
          explanation_fil?: string;
          id?: string;
          is_published?: boolean;
          key?: string;
          name_en?: string;
          name_fil?: string;
          points?: number;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      hotlines: {
        Row: {
          agency: string;
          area: string;
          created_at: string;
          id: string;
          is_active: boolean;
          is_verified: boolean;
          number: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          agency: string;
          area?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          is_verified?: boolean;
          number: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          agency?: string;
          area?: string;
          created_at?: string;
          id?: string;
          is_active?: boolean;
          is_verified?: boolean;
          number?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      level_versions: {
        Row: {
          config: Json;
          id: string;
          level_id: number;
          notes: string | null;
          published_at: string;
          published_by: string | null;
          version: number;
        };
        Insert: {
          config: Json;
          id?: string;
          level_id: number;
          notes?: string | null;
          published_at?: string;
          published_by?: string | null;
          version: number;
        };
        Update: {
          config?: Json;
          id?: string;
          level_id?: number;
          notes?: string | null;
          published_at?: string;
          published_by?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'level_versions_level_id_fkey';
            columns: ['level_id'];
            isOneToOne: false;
            referencedRelation: 'levels';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'level_versions_published_by_fkey';
            columns: ['published_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      levels: {
        Row: {
          created_at: string;
          current_version_id: string | null;
          id: number;
          is_active: boolean;
          name_en: string;
          name_fil: string;
          slug: string;
          sort_order: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          current_version_id?: string | null;
          id: number;
          is_active?: boolean;
          name_en: string;
          name_fil: string;
          slug: string;
          sort_order?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          current_version_id?: string | null;
          id?: number;
          is_active?: boolean;
          name_en?: string;
          name_fil?: string;
          slug?: string;
          sort_order?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'levels_current_version_fk';
            columns: ['current_version_id'];
            isOneToOne: false;
            referencedRelation: 'level_versions';
            referencedColumns: ['id'];
          },
        ];
      };
      live_sessions: {
        Row: {
          code: string;
          created_at: string;
          created_by: string;
          ended_at: string | null;
          group_id: string;
          id: string;
          level_id: number;
          started_at: string | null;
          status: string;
        };
        Insert: {
          code: string;
          created_at?: string;
          created_by?: string;
          ended_at?: string | null;
          group_id: string;
          id?: string;
          level_id: number;
          started_at?: string | null;
          status?: string;
        };
        Update: {
          code?: string;
          created_at?: string;
          created_by?: string;
          ended_at?: string | null;
          group_id?: string;
          id?: string;
          level_id?: number;
          started_at?: string | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'live_sessions_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'live_sessions_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'live_sessions_level_id_fkey';
            columns: ['level_id'];
            isOneToOne: false;
            referencedRelation: 'levels';
            referencedColumns: ['id'];
          },
        ];
      };
      notifications: {
        Row: {
          body: string;
          created_at: string;
          data: Json;
          id: string;
          read_at: string | null;
          title: string;
          type: string;
          user_id: string;
        };
        Insert: {
          body?: string;
          created_at?: string;
          data?: Json;
          id?: string;
          read_at?: string | null;
          title: string;
          type: string;
          user_id: string;
        };
        Update: {
          body?: string;
          created_at?: string;
          data?: Json;
          id?: string;
          read_at?: string | null;
          title?: string;
          type?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      npc_types: {
        Row: {
          created_at: string;
          id: string;
          is_published: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          needs: Json;
          points: number;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_published?: boolean;
          key: string;
          name_en: string;
          name_fil: string;
          needs?: Json;
          points?: number;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_published?: boolean;
          key?: string;
          name_en?: string;
          name_fil?: string;
          needs?: Json;
          points?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
      permissions: {
        Row: {
          id: number;
          name: string;
          requires_mfa: boolean;
        };
        Insert: {
          id: number;
          name: string;
          requires_mfa?: boolean;
        };
        Update: {
          id?: number;
          name?: string;
          requires_mfa?: boolean;
        };
        Relationships: [];
      };
      player_achievements: {
        Row: {
          achievement_id: string;
          unlocked_at: string;
          user_id: string;
        };
        Insert: {
          achievement_id: string;
          unlocked_at?: string;
          user_id: string;
        };
        Update: {
          achievement_id?: string;
          unlocked_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'player_achievements_achievement_id_fkey';
            columns: ['achievement_id'];
            isOneToOne: false;
            referencedRelation: 'achievements';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'player_achievements_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      player_cosmetics: {
        Row: {
          item_key: string;
          source: string;
          unlocked_at: string;
          user_id: string;
        };
        Insert: {
          item_key: string;
          source?: string;
          unlocked_at?: string;
          user_id: string;
        };
        Update: {
          item_key?: string;
          source?: string;
          unlocked_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'player_cosmetics_item_key_fkey';
            columns: ['item_key'];
            isOneToOne: false;
            referencedRelation: 'cosmetic_items';
            referencedColumns: ['key'];
          },
          {
            foreignKeyName: 'player_cosmetics_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      player_level_progress: {
        Row: {
          attempts_count: number;
          best_score: number;
          best_stars: number;
          level_id: number;
          unlocked: boolean;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          attempts_count?: number;
          best_score?: number;
          best_stars?: number;
          level_id: number;
          unlocked?: boolean;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          attempts_count?: number;
          best_score?: number;
          best_stars?: number;
          level_id?: number;
          unlocked?: boolean;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'player_level_progress_level_id_fkey';
            columns: ['level_id'];
            isOneToOne: false;
            referencedRelation: 'levels';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'player_level_progress_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      player_tips: {
        Row: {
          read_at: string | null;
          tip_id: string;
          unlocked_at: string;
          user_id: string;
        };
        Insert: {
          read_at?: string | null;
          tip_id: string;
          unlocked_at?: string;
          user_id: string;
        };
        Update: {
          read_at?: string | null;
          tip_id?: string;
          unlocked_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'player_tips_tip_id_fkey';
            columns: ['tip_id'];
            isOneToOne: false;
            referencedRelation: 'tips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'player_tips_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          avatar_config: Json;
          avatar_key: string | null;
          barangay: string | null;
          consent_at: string | null;
          created_at: string;
          deleted_at: string | null;
          display_name: string | null;
          id: string;
          is_minor: boolean | null;
          language: string;
          leaderboard_visible: boolean;
          onboarded_at: string | null;
          school: string | null;
          status: string;
          suspended_until: string | null;
          suspension_reason: string | null;
          updated_at: string;
          username: string;
        };
        Insert: {
          avatar_config?: Json;
          avatar_key?: string | null;
          barangay?: string | null;
          consent_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          display_name?: string | null;
          id: string;
          is_minor?: boolean | null;
          language?: string;
          leaderboard_visible?: boolean;
          onboarded_at?: string | null;
          school?: string | null;
          status?: string;
          suspended_until?: string | null;
          suspension_reason?: string | null;
          updated_at?: string;
          username: string;
        };
        Update: {
          avatar_config?: Json;
          avatar_key?: string | null;
          barangay?: string | null;
          consent_at?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          display_name?: string | null;
          id?: string;
          is_minor?: boolean | null;
          language?: string;
          leaderboard_visible?: boolean;
          onboarded_at?: string | null;
          school?: string | null;
          status?: string;
          suspended_until?: string | null;
          suspension_reason?: string | null;
          updated_at?: string;
          username?: string;
        };
        Relationships: [];
      };
      report_jobs: {
        Row: {
          completed_at: string | null;
          created_at: string;
          error: string | null;
          file_path: string | null;
          id: string;
          params: Json;
          requested_by: string;
          status: string;
          type: string;
        };
        Insert: {
          completed_at?: string | null;
          created_at?: string;
          error?: string | null;
          file_path?: string | null;
          id?: string;
          params?: Json;
          requested_by: string;
          status?: string;
          type: string;
        };
        Update: {
          completed_at?: string | null;
          created_at?: string;
          error?: string | null;
          file_path?: string | null;
          id?: string;
          params?: Json;
          requested_by?: string;
          status?: string;
          type?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'report_jobs_requested_by_fkey';
            columns: ['requested_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      role_permissions: {
        Row: {
          permission_id: number;
          role_id: number;
        };
        Insert: {
          permission_id: number;
          role_id: number;
        };
        Update: {
          permission_id?: number;
          role_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'role_permissions_permission_id_fkey';
            columns: ['permission_id'];
            isOneToOne: false;
            referencedRelation: 'permissions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'role_permissions_role_id_fkey';
            columns: ['role_id'];
            isOneToOne: false;
            referencedRelation: 'roles';
            referencedColumns: ['id'];
          },
        ];
      };
      roles: {
        Row: {
          id: number;
          name: string;
        };
        Insert: {
          id: number;
          name: string;
        };
        Update: {
          id?: number;
          name?: string;
        };
        Relationships: [];
      };
      streaks: {
        Row: {
          current: number;
          last_played_date: string | null;
          longest: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          current?: number;
          last_played_date?: string | null;
          longest?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          current?: number;
          last_played_date?: string | null;
          longest?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'streaks_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_blocks: {
        Row: {
          blocked_id: string;
          blocker_id: string;
          created_at: string;
        };
        Insert: {
          blocked_id: string;
          blocker_id: string;
          created_at?: string;
        };
        Update: {
          blocked_id?: string;
          blocker_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_blocks_blocked_id_fkey';
            columns: ['blocked_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_blocks_blocker_id_fkey';
            columns: ['blocker_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_chat_flags: {
        Row: {
          auto: boolean;
          created_at: string;
          id: string;
          reason: string;
          reviewed_at: string | null;
          reviewed_by: string | null;
          run_id: string | null;
          status: string;
          user_id: string;
        };
        Insert: {
          auto?: boolean;
          created_at?: string;
          id?: string;
          reason: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          run_id?: string | null;
          status?: string;
          user_id: string;
        };
        Update: {
          auto?: boolean;
          created_at?: string;
          id?: string;
          reason?: string;
          reviewed_at?: string | null;
          reviewed_by?: string | null;
          run_id?: string | null;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_chat_flags_reviewed_by_fkey';
            columns: ['reviewed_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_chat_flags_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_chat_flags_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_chat_messages: {
        Row: {
          body_delivered: string | null;
          body_original: string;
          created_at: string;
          filter_hits: string[];
          hidden_at: string | null;
          hidden_by: string | null;
          id: number;
          run_id: string;
          sender_id: string;
          session_id: string | null;
          status: string;
        };
        Insert: {
          body_delivered?: string | null;
          body_original: string;
          created_at?: string;
          filter_hits?: string[];
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: number;
          run_id: string;
          sender_id: string;
          session_id?: string | null;
          status: string;
        };
        Update: {
          body_delivered?: string | null;
          body_original?: string;
          created_at?: string;
          filter_hits?: string[];
          hidden_at?: string | null;
          hidden_by?: string | null;
          id?: number;
          run_id?: string;
          sender_id?: string;
          session_id?: string | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_chat_messages_hidden_by_fkey';
            columns: ['hidden_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_chat_messages_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_chat_messages_sender_id_fkey';
            columns: ['sender_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_chat_messages_session_id_fkey';
            columns: ['session_id'];
            isOneToOne: false;
            referencedRelation: 'survival_sessions';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_config_versions: {
        Row: {
          config: Json;
          id: string;
          is_current: boolean;
          notes: string | null;
          published_at: string;
          published_by: string | null;
          version: number;
        };
        Insert: {
          config: Json;
          id?: string;
          is_current?: boolean;
          notes?: string | null;
          published_at?: string;
          published_by?: string | null;
          version: number;
        };
        Update: {
          config?: Json;
          id?: string;
          is_current?: boolean;
          notes?: string | null;
          published_at?: string;
          published_by?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_config_versions_published_by_fkey';
            columns: ['published_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_learning_events: {
        Row: {
          created_at: string;
          day: number;
          event_key: string;
          id: number;
          is_positive: boolean;
          run_id: string;
          user_id: string | null;
        };
        Insert: {
          created_at?: string;
          day: number;
          event_key: string;
          id?: number;
          is_positive: boolean;
          run_id: string;
          user_id?: string | null;
        };
        Update: {
          created_at?: string;
          day?: number;
          event_key?: string;
          id?: number;
          is_positive?: boolean;
          run_id?: string;
          user_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_learning_events_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_learning_events_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_mutes: {
        Row: {
          created_at: string;
          muted_id: string;
          muter_id: string;
        };
        Insert: {
          created_at?: string;
          muted_id: string;
          muter_id: string;
        };
        Update: {
          created_at?: string;
          muted_id?: string;
          muter_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_mutes_muted_id_fkey';
            columns: ['muted_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_mutes_muter_id_fkey';
            columns: ['muter_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_player_stats: {
        Row: {
          boat_stages_built: number;
          full_rescues: number;
          nights_survived: number;
          revives_given: number;
          runs_completed: number;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          boat_stages_built?: number;
          full_rescues?: number;
          nights_survived?: number;
          revives_given?: number;
          runs_completed?: number;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          boat_stages_built?: number;
          full_rescues?: number;
          nights_survived?: number;
          revives_given?: number;
          runs_completed?: number;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_player_stats_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_reports: {
        Row: {
          created_at: string;
          evidence: Json;
          id: string;
          message_id: number | null;
          priority: string;
          reason: string;
          reported_id: string;
          reporter_id: string;
          review_note: string | null;
          reviewed_at: string | null;
          reviewer_id: string | null;
          run_id: string | null;
          status: string;
        };
        Insert: {
          created_at?: string;
          evidence?: Json;
          id?: string;
          message_id?: number | null;
          priority?: string;
          reason: string;
          reported_id: string;
          reporter_id: string;
          review_note?: string | null;
          reviewed_at?: string | null;
          reviewer_id?: string | null;
          run_id?: string | null;
          status?: string;
        };
        Update: {
          created_at?: string;
          evidence?: Json;
          id?: string;
          message_id?: number | null;
          priority?: string;
          reason?: string;
          reported_id?: string;
          reporter_id?: string;
          review_note?: string | null;
          reviewed_at?: string | null;
          reviewer_id?: string | null;
          run_id?: string | null;
          status?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_reports_message_id_fkey';
            columns: ['message_id'];
            isOneToOne: false;
            referencedRelation: 'survival_chat_messages';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_reports_reported_id_fkey';
            columns: ['reported_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_reports_reporter_id_fkey';
            columns: ['reporter_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_reports_reviewer_id_fkey';
            columns: ['reviewer_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_reports_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_restrictions: {
        Row: {
          created_at: string;
          created_by: string | null;
          ends_at: string | null;
          id: string;
          lifted_notified: boolean;
          reason: string;
          revoked_at: string | null;
          revoked_by: string | null;
          scope: string;
          starts_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          ends_at?: string | null;
          id?: string;
          lifted_notified?: boolean;
          reason: string;
          revoked_at?: string | null;
          revoked_by?: string | null;
          scope: string;
          starts_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          ends_at?: string | null;
          id?: string;
          lifted_notified?: boolean;
          reason?: string;
          revoked_at?: string | null;
          revoked_by?: string | null;
          scope?: string;
          starts_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_restrictions_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_restrictions_revoked_by_fkey';
            columns: ['revoked_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_restrictions_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_results: {
        Row: {
          created_at: string;
          days_survived: number;
          difficulty: string;
          ending: string;
          final_score: number;
          learning_summary: Json;
          per_player: Json;
          real_minutes_played: number;
          run_id: string;
          team_size: number;
          verified: boolean;
        };
        Insert: {
          created_at?: string;
          days_survived: number;
          difficulty: string;
          ending: string;
          final_score: number;
          learning_summary?: Json;
          per_player?: Json;
          real_minutes_played: number;
          run_id: string;
          team_size: number;
          verified?: boolean;
        };
        Update: {
          created_at?: string;
          days_survived?: number;
          difficulty?: string;
          ending?: string;
          final_score?: number;
          learning_summary?: Json;
          per_player?: Json;
          real_minutes_played?: number;
          run_id?: string;
          team_size?: number;
          verified?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_results_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: true;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_run_members: {
        Row: {
          deaths: number;
          joined_at: string;
          left_at: string | null;
          revives_given: number;
          role: string;
          run_id: string;
          status: string;
          user_id: string;
        };
        Insert: {
          deaths?: number;
          joined_at?: string;
          left_at?: string | null;
          revives_given?: number;
          role?: string;
          run_id: string;
          status?: string;
          user_id: string;
        };
        Update: {
          deaths?: number;
          joined_at?: string;
          left_at?: string | null;
          revives_given?: number;
          role?: string;
          run_id?: string;
          status?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_run_members_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_run_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_runs: {
        Row: {
          boat_stage: number;
          config_version_id: string;
          created_at: string;
          current_day: number;
          difficulty: string;
          ended_at: string | null;
          ending: string | null;
          expiry_warned: boolean;
          final_score: number | null;
          flags: string[];
          host_id: string;
          id: string;
          last_session_at: string | null;
          mode: string;
          seed: number;
          status: string;
          updated_at: string;
        };
        Insert: {
          boat_stage?: number;
          config_version_id: string;
          created_at?: string;
          current_day?: number;
          difficulty: string;
          ended_at?: string | null;
          ending?: string | null;
          expiry_warned?: boolean;
          final_score?: number | null;
          flags?: string[];
          host_id: string;
          id?: string;
          last_session_at?: string | null;
          mode: string;
          seed: number;
          status?: string;
          updated_at?: string;
        };
        Update: {
          boat_stage?: number;
          config_version_id?: string;
          created_at?: string;
          current_day?: number;
          difficulty?: string;
          ended_at?: string | null;
          ending?: string | null;
          expiry_warned?: boolean;
          final_score?: number | null;
          flags?: string[];
          host_id?: string;
          id?: string;
          last_session_at?: string | null;
          mode?: string;
          seed?: number;
          status?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_runs_config_version_id_fkey';
            columns: ['config_version_id'];
            isOneToOne: false;
            referencedRelation: 'survival_config_versions';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_runs_host_id_fkey';
            columns: ['host_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_sessions: {
        Row: {
          end_reason: string | null;
          ended_at: string | null;
          id: string;
          room_id: string;
          run_id: string;
          started_at: string;
        };
        Insert: {
          end_reason?: string | null;
          ended_at?: string | null;
          id?: string;
          room_id: string;
          run_id: string;
          started_at?: string;
        };
        Update: {
          end_reason?: string | null;
          ended_at?: string | null;
          id?: string;
          room_id?: string;
          run_id?: string;
          started_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_sessions_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_snapshots: {
        Row: {
          byte_size: number;
          created_at: string;
          day: number;
          id: string;
          run_id: string;
          state: Json | null;
          state_gz: string | null;
          time_of_day: number;
        };
        Insert: {
          byte_size: number;
          created_at?: string;
          day: number;
          id?: string;
          run_id: string;
          state?: Json | null;
          state_gz?: string | null;
          time_of_day: number;
        };
        Update: {
          byte_size?: number;
          created_at?: string;
          day?: number;
          id?: string;
          run_id?: string;
          state?: Json | null;
          state_gz?: string | null;
          time_of_day?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_snapshots_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: false;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
        ];
      };
      system_settings: {
        Row: {
          is_public: boolean;
          key: string;
          updated_at: string;
          updated_by: string | null;
          value: Json;
        };
        Insert: {
          is_public?: boolean;
          key: string;
          updated_at?: string;
          updated_by?: string | null;
          value: Json;
        };
        Update: {
          is_public?: boolean;
          key?: string;
          updated_at?: string;
          updated_by?: string | null;
          value?: Json;
        };
        Relationships: [
          {
            foreignKeyName: 'system_settings_updated_by_fkey';
            columns: ['updated_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      tips: {
        Row: {
          body_en: string;
          body_fil: string;
          category: string;
          created_at: string;
          id: string;
          is_published: boolean;
          needs_verification: boolean;
          slug: string;
          sort_order: number;
          title_en: string;
          title_fil: string;
          unlock_rule: Json;
          updated_at: string;
        };
        Insert: {
          body_en: string;
          body_fil: string;
          category: string;
          created_at?: string;
          id?: string;
          is_published?: boolean;
          needs_verification?: boolean;
          slug: string;
          sort_order?: number;
          title_en: string;
          title_fil: string;
          unlock_rule?: Json;
          updated_at?: string;
        };
        Update: {
          body_en?: string;
          body_fil?: string;
          category?: string;
          created_at?: string;
          id?: string;
          is_published?: boolean;
          needs_verification?: boolean;
          slug?: string;
          sort_order?: number;
          title_en?: string;
          title_fil?: string;
          unlock_rule?: Json;
          updated_at?: string;
        };
        Relationships: [];
      };
      user_devices: {
        Row: {
          created_at: string;
          device_name: string | null;
          id: string;
          last_seen_at: string;
          platform: string;
          push_token_encrypted: string | null;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          device_name?: string | null;
          id?: string;
          last_seen_at?: string;
          platform: string;
          push_token_encrypted?: string | null;
          user_id: string;
        };
        Update: {
          created_at?: string;
          device_name?: string | null;
          id?: string;
          last_seen_at?: string;
          platform?: string;
          push_token_encrypted?: string | null;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_devices_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      user_roles: {
        Row: {
          granted_at: string;
          granted_by: string | null;
          role_id: number;
          user_id: string;
        };
        Insert: {
          granted_at?: string;
          granted_by?: string | null;
          role_id: number;
          user_id: string;
        };
        Update: {
          granted_at?: string;
          granted_by?: string | null;
          role_id?: number;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_roles_granted_by_fkey';
            columns: ['granted_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_roles_role_id_fkey';
            columns: ['role_id'];
            isOneToOne: false;
            referencedRelation: 'roles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'user_roles_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      user_settings: {
        Row: {
          audio: Json;
          controls: Json;
          graphics_quality: string;
          notifications: Json;
          reduced_motion: boolean;
          survival_chat_mode: string;
          text_scale: number;
          theme: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          audio?: Json;
          controls?: Json;
          graphics_quality?: string;
          notifications?: Json;
          reduced_motion?: boolean;
          survival_chat_mode?: string;
          text_scale?: number;
          theme?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          audio?: Json;
          controls?: Json;
          graphics_quality?: string;
          notifications?: Json;
          reduced_motion?: boolean;
          survival_chat_mode?: string;
          text_scale?: number;
          theme?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'user_settings_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: true;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      group_progress_view: {
        Row: {
          attempts_count: number | null;
          avatar_key: string | null;
          best_score: number | null;
          best_stars: number | null;
          group_id: string | null;
          level_id: number | null;
          member_status: string | null;
          updated_at: string | null;
          user_id: string | null;
          username: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey';
            columns: ['group_id'];
            isOneToOne: false;
            referencedRelation: 'groups';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'group_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'player_level_progress_level_id_fkey';
            columns: ['level_id'];
            isOneToOne: false;
            referencedRelation: 'levels';
            referencedColumns: ['id'];
          },
        ];
      };
      leaderboard_all_time: {
        Row: {
          last_at: string | null;
          level_key: number | null;
          score: number | null;
          stars: number | null;
          user_id: string | null;
        };
        Relationships: [];
      };
      leaderboard_weekly: {
        Row: {
          last_at: string | null;
          level_key: number | null;
          score: number | null;
          stars: number | null;
          user_id: string | null;
        };
        Relationships: [];
      };
      survival_leaderboard_all_time: {
        Row: {
          difficulty: string | null;
          ended_at: string | null;
          ending: string | null;
          final_score: number | null;
          host_id: string | null;
          real_minutes_played: number | null;
          run_id: string | null;
          team_size: number | null;
          team_type: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_results_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: true;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_runs_host_id_fkey';
            columns: ['host_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      survival_leaderboard_weekly: {
        Row: {
          difficulty: string | null;
          ended_at: string | null;
          ending: string | null;
          final_score: number | null;
          host_id: string | null;
          real_minutes_played: number | null;
          run_id: string | null;
          team_size: number | null;
          team_type: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'survival_results_run_id_fkey';
            columns: ['run_id'];
            isOneToOne: true;
            referencedRelation: 'survival_runs';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'survival_runs_host_id_fkey';
            columns: ['host_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Functions: {
      abandon_stale_attempts: { Args: never; Returns: number };
      admin_kpis: { Args: never; Returns: Json };
      admin_reset_mfa: { Args: { p_user_id: string }; Returns: number };
      admin_revoke_sessions: { Args: { p_user_id: string }; Returns: number };
      admin_search_users: {
        Args: {
          p_limit?: number;
          p_offset?: number;
          p_query?: string;
          p_status?: string;
        };
        Returns: {
          attempts: number;
          created_at: string;
          email: string;
          id: string;
          mfa: boolean;
          roles: string[];
          status: string;
          suspended_until: string;
          suspension_reason: string;
          total: number;
          username: string;
        }[];
      };
      admin_set_user_status: {
        Args: {
          p_reason?: string;
          p_status: string;
          p_until?: string;
          p_user_id: string;
        };
        Returns: undefined;
      };
      assignment_progress: {
        Args: { p_assignment_id: string };
        Returns: {
          best_stars: number;
          done: boolean;
          user_id: string;
          username: string;
        }[];
      };
      authorize: { Args: { requested_permission: string }; Returns: boolean };
      can_access_live_session: { Args: { sid: string }; Returns: boolean };
      can_play_survival: { Args: { uid: string }; Returns: boolean };
      can_view_group: { Args: { gid: string }; Returns: boolean };
      chat_restricted: { Args: { uid: string }; Returns: boolean };
      current_request_ip: { Args: never; Returns: unknown };
      custom_access_token_hook: { Args: { event: Json }; Returns: Json };
      email_outbox_retry: { Args: never; Returns: undefined };
      enqueue_email: {
        Args: {
          p_critical?: boolean;
          p_params?: Json;
          p_template: string;
          p_user_id: string;
        };
        Returns: undefined;
      };
      expire_reports: { Args: never; Returns: undefined };
      facilitator_overview: { Args: { p_group_id?: string }; Returns: Json };
      finalize_attempt: {
        Args: { p_attempt_id: string; p_result: Json };
        Returns: Json;
      };
      flagged_attempts: {
        Args: { p_include_voided?: boolean };
        Returns: {
          finished_at: string;
          flag_reasons: string[];
          id: string;
          level_id: number;
          score: number;
          stars: number;
          started_at: string;
          status: string;
          user_id: string;
          username: string;
          void_reason: string;
        }[];
      };
      generate_code6: { Args: never; Returns: string };
      generate_daily_challenge: {
        Args: { p_date?: string };
        Returns: undefined;
      };
      get_group_roster: {
        Args: { p_group_id: string };
        Returns: {
          avatar_config: Json;
          joined_at: string;
          last_played: string;
          levels_done: number;
          stars: number;
          status: string;
          user_id: string;
          username: string;
        }[];
      };
      get_leaderboard: {
        Args: {
          p_cursor?: number;
          p_group_id?: string;
          p_level_id?: number;
          p_limit?: number;
          p_only_me?: boolean;
          p_period?: string;
          p_scope?: string;
        };
        Returns: {
          avatar_config: Json;
          avatar_key: string;
          barangay: string;
          is_me: boolean;
          rank: number;
          score: number;
          stars: number;
          user_id: string;
          username: string;
        }[];
      };
      get_public_profiles: {
        Args: { p_ids: string[] };
        Returns: {
          avatar_config: Json;
          avatar_key: string;
          id: string;
          username: string;
        }[];
      };
      get_report_chat_evidence: {
        Args: { p_report_id: string };
        Returns: {
          body_delivered: string;
          body_original: string;
          created_at: string;
          filter_hits: string[];
          id: number;
          sender_id: string;
          sender_username: string;
          status: string;
        }[];
      };
      get_survival_leaderboard: {
        Args: {
          p_cursor?: number;
          p_difficulty: string;
          p_limit?: number;
          p_period?: string;
          p_team_type: string;
        };
        Returns: {
          ended_at: string;
          ending: string;
          final_score: number;
          members: Json;
          rank: number;
          real_minutes_played: number;
          run_id: string;
          team_size: number;
        }[];
      };
      group_analytics: {
        Args: {
          p_from?: string;
          p_group_id: string;
          p_level_id?: number;
          p_to?: string;
        };
        Returns: Json;
      };
      has_role: { Args: { role_name: string }; Returns: boolean };
      has_staff_role: { Args: { uid: string }; Returns: boolean };
      is_active_user: { Args: never; Returns: boolean };
      is_group_member: { Args: { gid: string }; Returns: boolean };
      is_group_owner: { Args: { gid: string }; Returns: boolean };
      is_my_active_group_member: { Args: { uid: string }; Returns: boolean };
      is_my_group_member: { Args: { uid: string }; Returns: boolean };
      is_survival_member: { Args: { rid: string }; Returns: boolean };
      is_username_available: { Args: { p_username: string }; Returns: boolean };
      join_group: { Args: { code: string }; Returns: Json };
      leaderboard_eligible: {
        Args: { p_since: string };
        Returns: {
          best_score: number;
          best_stars: number;
          last_at: string;
          level_id: number;
          user_id: string;
        }[];
      };
      list_my_survival_runs: {
        Args: never;
        Returns: {
          boat_stage: number;
          created_at: string;
          current_day: number;
          difficulty: string;
          ending: string;
          final_score: number;
          is_host: boolean;
          last_session_at: string;
          mode: string;
          run_id: string;
          status: string;
          teammates: Json;
        }[];
      };
      moderate_attempt: {
        Args: { p_action: string; p_attempt_id: string; p_reason: string };
        Returns: undefined;
      };
      notify_user: {
        Args: {
          p_body?: string;
          p_data?: Json;
          p_title: string;
          p_type: string;
          p_user_id: string;
        };
        Returns: string;
      };
      publish_level_version: {
        Args: { p_config: Json; p_level_id: number; p_notes?: string };
        Returns: string;
      };
      purge_deleted_accounts: { Args: never; Returns: number };
      realtime_topic_id: { Args: { prefix: string }; Returns: string };
      recompute_progress: {
        Args: { p_level_id: number; p_user_id: string };
        Returns: undefined;
      };
      refresh_leaderboards: { Args: never; Returns: undefined };
      refresh_survival_leaderboards: { Args: never; Returns: undefined };
      regenerate_join_code: { Args: { gid: string }; Returns: string };
      remind_assignments: { Args: never; Returns: undefined };
      security_overview: { Args: never; Returns: Json };
      super_set_admin: {
        Args: { p_make_admin: boolean; p_user_id: string };
        Returns: undefined;
      };
      survival_maintenance: { Args: never; Returns: undefined };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
