// Writes the Survival config v1 seed migration from the typed defaults (validated first), so
// the SQL seed can never drift from packages/shared/src/survival/default-config.ts.
// Usage: pnpm exec tsx scripts/gen-survival-seed.ts
import fs from 'node:fs';
import {
  DEFAULT_SURVIVAL_CONFIG,
  survivalConfigSchema,
} from '../packages/shared/src/survival/index.ts';

const parsed = survivalConfigSchema.parse(DEFAULT_SURVIVAL_CONFIG);
const json = JSON.stringify(parsed).replace(/'/g, "''");
const out = 'supabase/migrations/20261001000200_survival_seed_config.sql';
fs.writeFileSync(
  out,
  `-- Survival config v1 (generated by scripts/gen-survival-seed.ts from the typed defaults).
-- Health lessons inside are marked for review: VERIFY WITH DOH/MDRRMO before public release.
insert into public.survival_config_versions (version, config, is_current, notes)
values (1, '${json}'::jsonb, true, 'Seed: Section 5 defaults + owner add-ons (axe, jump, no-slow-motion sprint).')
on conflict (version) do nothing;
`,
);
console.log(`✔ wrote ${out} (${(json.length / 1024).toFixed(1)} KB config)`);
