// Generates Supabase TypeScript types for the linked project into apps/web and packages/shared.
import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import dotenv from 'dotenv';

dotenv.config({ path: path.resolve('.env.local'), quiet: true });
const out = execSync('pnpm exec supabase gen types typescript --linked --schema public', {
  encoding: 'utf8',
  env: process.env,
  maxBuffer: 20e6,
});
const header = '// AUTO-GENERATED by `pnpm db:types`. Do not edit by hand.\n';
for (const target of [
  'apps/web/lib/supabase/database.types.ts',
  'packages/shared/src/database.types.ts',
]) {
  fs.writeFileSync(target, header + out);
  console.log(`✔ wrote ${target}`);
}
