import { DEFAULT_ACTIONS, DEFAULT_CAMERA } from '../level-config.ts';
import {
  DEFAULT_CAMP_UPGRADES,
  DEFAULT_EVENTS,
  DEFAULT_HAZARDS,
  type BoatStageDef,
  type RecipeDef,
  type SurvivalConfig,
} from './config.ts';
import { DEFAULT_ITEMS } from './items.ts';

/** Seed recipes (Normal, solo; scaled by difficulty and team size at runtime). */
export const DEFAULT_RECIPES: RecipeDef[] = [
  {
    key: 'bandage',
    name: { fil: 'Benda', en: 'Bandage' },
    inputs: [{ item: 'clean_cloth', qty: 2 }],
    tools: [],
    output: { item: 'bandage', qty: 1 },
    where: 'anywhere',
    needsFire: false,
    seconds: 3,
  },
  {
    key: 'water_filter',
    name: { fil: 'Panala ng tubig', en: 'Water filter' },
    inputs: [
      { item: 'empty_bottle', qty: 1 },
      { item: 'cloth', qty: 1 },
      { item: 'sand', qty: 1 },
      { item: 'charcoal', qty: 1 },
    ],
    tools: [],
    output: { item: 'water_filter', qty: 1 },
    where: 'camp',
    needsFire: false,
    seconds: 6,
    // VERIFY WITH DOH/MDRRMO
    lesson: {
      fil: 'Salain ang tubig, pero pakuluan pa rin kung kaya.',
      en: 'Filter water, but still boil it when you can.',
    },
  },
  {
    key: 'filtered_water',
    name: { fil: 'Sinalang tubig', en: 'Filtered water' },
    inputs: [{ item: 'dirty_water', qty: 1 }],
    tools: ['water_filter'],
    output: { item: 'filtered_water', qty: 1 },
    where: 'anywhere',
    needsFire: false,
    seconds: 3,
  },
  {
    key: 'boiled_water',
    name: { fil: 'Pakuluan ang tubig', en: 'Boil water' },
    inputs: [{ item: 'dirty_water', qty: 1 }],
    tools: ['cooking_pot'],
    output: { item: 'boiled_water', qty: 1 },
    where: 'camp',
    needsFire: true,
    seconds: 5,
    // VERIFY WITH DOH/MDRRMO
    lesson: {
      fil: 'Ang pinakuluang tubig ang pinakaligtas inumin sa panahon ng baha.',
      en: 'Boiled water is the safest to drink during floods.',
    },
  },
  {
    key: 'campfire',
    name: { fil: 'Siga', en: 'Campfire' },
    inputs: [{ item: 'wood', qty: 3 }],
    tools: ['lighter'],
    structure: 'campfire',
    where: 'camp',
    needsFire: false,
    seconds: 5,
  },
  {
    key: 'charcoal',
    name: { fil: 'Uling', en: 'Charcoal' },
    inputs: [{ item: 'wood', qty: 1 }],
    tools: [],
    output: { item: 'charcoal', qty: 2 },
    where: 'camp',
    needsFire: true,
    seconds: 6,
  },
  {
    key: 'torch',
    name: { fil: 'Sulo', en: 'Torch' },
    inputs: [
      { item: 'wood', qty: 1 },
      { item: 'cloth', qty: 1 },
    ],
    tools: [],
    output: { item: 'torch', qty: 1 },
    where: 'camp',
    needsFire: true,
    seconds: 3,
  },
  {
    key: 'cooked_fish',
    name: { fil: 'Iluto ang isda', en: 'Cook fish' },
    inputs: [{ item: 'raw_fish', qty: 1 }],
    tools: [],
    output: { item: 'cooked_fish', qty: 1 },
    where: 'camp',
    needsFire: true,
    seconds: 5,
  },
  {
    key: 'cooked_rice',
    name: { fil: 'Magsaing', en: 'Cook rice' },
    inputs: [
      { item: 'rice', qty: 1 },
      { item: 'boiled_water', qty: 1 },
    ],
    tools: ['cooking_pot'],
    output: { item: 'cooked_rice', qty: 2 },
    where: 'camp',
    needsFire: true,
    seconds: 8,
  },
  {
    key: 'tarp_shelter',
    name: { fil: 'Silungang trapal', en: 'Tarp shelter' },
    inputs: [
      { item: 'tarp', qty: 2 },
      { item: 'rope', qty: 2 },
      { item: 'wood', qty: 4 },
    ],
    tools: [],
    structure: 'shelter',
    where: 'camp',
    needsFire: false,
    seconds: 20,
  },
  {
    key: 'rain_catcher',
    name: { fil: 'Saluhan ng ulan', en: 'Rain catcher' },
    inputs: [
      { item: 'tarp', qty: 1 },
      { item: 'plastic_drum', qty: 1 },
    ],
    tools: [],
    structure: 'rain_catcher',
    where: 'camp',
    needsFire: false,
    seconds: 10,
  },
  {
    key: 'fishing_rod',
    name: { fil: 'Pamingwit', en: 'Fishing rod' },
    inputs: [
      { item: 'bamboo', qty: 1 },
      { item: 'string', qty: 1 },
    ],
    tools: [],
    output: { item: 'fishing_rod', qty: 1 },
    where: 'anywhere',
    needsFire: false,
    seconds: 6,
  },
  {
    key: 'axe',
    name: { fil: 'Palakol', en: 'Axe' },
    inputs: [
      { item: 'wood', qty: 2 },
      { item: 'metal_sheet', qty: 1 },
      { item: 'rope', qty: 1 },
    ],
    tools: ['hammer'],
    output: { item: 'axe', qty: 1 },
    where: 'camp',
    needsFire: false,
    seconds: 12,
  },
  {
    key: 'makeshift_raft',
    name: { fil: 'Balsa', en: 'Makeshift raft' },
    inputs: [
      { item: 'wood', qty: 4 },
      { item: 'plastic_drum', qty: 2 },
      { item: 'rope', qty: 2 },
    ],
    tools: [],
    structure: 'raft',
    where: 'camp',
    needsFire: false,
    seconds: 25,
  },
  {
    key: 'sos_sign',
    name: { fil: 'SOS na karatula', en: 'SOS sign' },
    inputs: [
      { item: 'bright_cloth', qty: 2 },
      { item: 'wood', qty: 4 },
    ],
    tools: [],
    structure: 'sos_sign',
    where: 'signal_spot',
    needsFire: false,
    seconds: 15,
    lesson: {
      fil: 'Gumamit ng maliwanag na kulay para makita ng rescuers.',
      en: 'Use bright colors so rescuers can see you.',
    },
  },
  {
    key: 'signal_fire_pile',
    name: { fil: 'Siga-senyales', en: 'Signal fire pile' },
    inputs: [
      { item: 'wood', qty: 6 },
      { item: 'cloth', qty: 2 },
    ],
    tools: [],
    structure: 'signal_fire',
    where: 'signal_spot',
    needsFire: false,
    seconds: 15,
    lesson: {
      fil: 'Apoy, salamin, o pito — gamitin para makita at marinig ng rescuers.',
      en: 'Fire, a mirror or a whistle help rescuers see and hear you.',
    },
  },
  {
    key: 'storage_cover',
    name: { fil: 'Takip ng imbakan', en: 'Storage tarp cover' },
    inputs: [
      { item: 'tarp', qty: 1 },
      { item: 'rope', qty: 2 },
    ],
    tools: [],
    structure: 'storage_cover',
    where: 'camp',
    needsFire: false,
    seconds: 10,
  },
  {
    key: 'build_site_cover',
    name: { fil: 'Takip ng bangka', en: 'Boat site cover' },
    inputs: [
      { item: 'tarp', qty: 1 },
      { item: 'rope', qty: 2 },
    ],
    tools: [],
    structure: 'boat_cover',
    where: 'camp',
    needsFire: false,
    seconds: 10,
  },
];

export const DEFAULT_BOAT_STAGES: BoatStageDef[] = [
  {
    stage: 1,
    name: { fil: 'Balangkas', en: 'Frame' },
    materials: [
      { item: 'wood', qty: 12 },
      { item: 'nails', qty: 20 },
    ],
    tools: ['hammer'],
    workSeconds: 60,
    targetDay: 5,
    workbench2: false,
  },
  {
    stage: 2,
    name: { fil: 'Sahig', en: 'Hull & floor' },
    materials: [
      { item: 'wood', qty: 15 },
      { item: 'nails', qty: 30 },
      { item: 'metal_sheet', qty: 2 },
    ],
    tools: ['hammer'],
    workSeconds: 90,
    targetDay: 10,
    workbench2: false,
  },
  {
    stage: 3,
    name: { fil: 'Pampalutang', en: 'Flotation' },
    materials: [
      { item: 'plastic_drum', qty: 6 },
      { item: 'rope', qty: 4 },
    ],
    tools: [],
    workSeconds: 60,
    targetDay: 15,
    workbench2: true,
  },
  {
    stage: 4,
    name: { fil: 'Pantali at Pampatibay', en: 'Lashing' },
    materials: [
      { item: 'rope', qty: 8 },
      { item: 'bamboo', qty: 4 },
    ],
    tools: [],
    workSeconds: 75,
    targetDay: 20,
    workbench2: true,
  },
  {
    stage: 5,
    name: { fil: 'Sagwan', en: 'Paddles' },
    materials: [
      { item: 'wood', qty: 4 },
      { item: 'bamboo', qty: 2 },
    ],
    tools: ['knife'],
    workSeconds: 45,
    targetDay: 24,
    workbench2: true,
  },
  {
    stage: 6,
    name: { fil: 'Layag at Tapal', en: 'Sail & waterproofing' },
    materials: [
      { item: 'tarp', qty: 2 },
      { item: 'cloth', qty: 3 },
      { item: 'rope', qty: 2 },
    ],
    tools: [],
    workSeconds: 60,
    targetDay: 28,
    workbench2: true,
  },
];

/** Section 5 seed values. Runs pin a config version; admins publish new versions. */
export const DEFAULT_SURVIVAL_CONFIG: SurvivalConfig = {
  difficulties: {
    easy: {
      minutesPerDay: 9,
      lootMultiplier: 1.5,
      hungerDrainMul: 0.7,
      thirstDrainMul: 0.7,
      nightColdMul: 0.7,
      stormDays: [10, 20],
      randomStorms: 0,
      waterRisePerStorm: 0.15,
      bleedOutSec: 60,
      deathPenalty: 'keep_bag',
      secondWinds: 3,
      boatMaterialMul: 0.8,
      supplyDropEveryDays: 3,
      hazardDensity: 0.6,
      heliWindow: { start: 6, end: 18 },
      rewardMultiplier: 1,
    },
    normal: {
      minutesPerDay: 8,
      lootMultiplier: 1,
      hungerDrainMul: 1,
      thirstDrainMul: 1,
      nightColdMul: 1,
      stormDays: [8, 16, 24],
      randomStorms: 0,
      waterRisePerStorm: 0.25,
      bleedOutSec: 45,
      deathPenalty: 'drop_bag',
      secondWinds: 2,
      boatMaterialMul: 1,
      supplyDropEveryDays: 5,
      hazardDensity: 1,
      heliWindow: { start: 8, end: 16 },
      rewardMultiplier: 1.5,
    },
    hard: {
      minutesPerDay: 7,
      lootMultiplier: 0.6,
      hungerDrainMul: 1.4,
      thirstDrainMul: 1.4,
      nightColdMul: 1.4,
      stormDays: [6, 12, 18, 24],
      randomStorms: 2,
      waterRisePerStorm: 0.35,
      bleedOutSec: 30,
      deathPenalty: 'permadeath',
      secondWinds: 1,
      boatMaterialMul: 1.3,
      supplyDropEveryDays: 7,
      hazardDensity: 1.5,
      heliWindow: { start: 10, end: 14 },
      rewardMultiplier: 2.5,
    },
  },
  stats: {
    hungerPerHour: 3.5,
    thirstPerHour: 5,
    thirstHeatMul: 1.3,
    warmthNightPerHour: 6,
    warmthWetPerHour: 5,
    warmthRecoverPerHour: 30,
    energyAwakePerHour: 2.5,
    energySleepPerHour: 15,
    starvingHealthPerHour: 6,
    dehydratedHealthPerHour: 9,
    hypothermiaHealthPerHour: 8,
    healthRegenPerHour: 2,
    energyUnlockAt: 15,
    leptoRiskPerMinute: 0.8,
    unsafeWaterSicknessChance: 0.6,
  },
  bag: { slots: 12, quickSlots: 4, maxWeightKg: 15, slowAtRatio: 0.8, slowMultiplier: 0.85 },
  items: DEFAULT_ITEMS,
  recipes: DEFAULT_RECIPES,
  boatStages: DEFAULT_BOAT_STAGES,
  roles: {
    medic: {
      reviveSpeedMul: 1 / 0.6,
      healMul: 1.5,
      buildSpeedMul: 1,
      materialSaveRatio: 0,
      swimSpeedMul: 1,
      lootHighlightRadiusM: 0,
      cookHungerMul: 1,
      earlyWarningMin: 0,
    },
    builder: {
      reviveSpeedMul: 1,
      healMul: 1,
      buildSpeedMul: 1.35,
      materialSaveRatio: 0.15,
      swimSpeedMul: 1,
      lootHighlightRadiusM: 0,
      cookHungerMul: 1,
      earlyWarningMin: 0,
    },
    scout: {
      reviveSpeedMul: 1,
      healMul: 1,
      buildSpeedMul: 1,
      materialSaveRatio: 0,
      swimSpeedMul: 1.2,
      lootHighlightRadiusM: 25,
      cookHungerMul: 1,
      earlyWarningMin: 0,
    },
    cook: {
      reviveSpeedMul: 1,
      healMul: 1,
      buildSpeedMul: 1,
      materialSaveRatio: 0,
      swimSpeedMul: 1,
      lootHighlightRadiusM: 0,
      cookHungerMul: 1.4,
      earlyWarningMin: 0,
    },
    radio: {
      reviveSpeedMul: 1,
      healMul: 1,
      buildSpeedMul: 1,
      materialSaveRatio: 0,
      swimSpeedMul: 1,
      lootHighlightRadiusM: 0,
      cookHungerMul: 1,
      earlyWarningMin: 120,
    },
  },
  melee: {
    axeRangeM: 2,
    axeArcDeg: 100,
    axeCooldownSec: 0.6,
    axeStaminaCost: 3,
    woodPerChop: 1,
    shoveRangeM: 1.2,
    shoveCooldownSec: 0.8,
    shoveStaminaCost: 2,
  },
  actions: { ...DEFAULT_ACTIONS },
  camera: { ...DEFAULT_CAMERA },
  chat: {
    maxLength: 150,
    minIntervalMs: 1500,
    perMinute: 20,
    duplicateLimit: 3,
    autoMuteHits: 3,
    autoMuteWindowMin: 5,
    muteMinutes: [10, 30, 120],
    quickChatIntervalMs: 2000,
    pingIntervalMs: 2000,
    retentionDays: 14,
  },
  session: {
    maxPlayers: 5,
    minCoopPlayers: 2,
    totalDays: 30,
    startHour: 6,
    dawnHour: 5,
    nightStartHour: 19,
    autoSaveEverySec: 120,
    reconnectSec: 120,
    lobbyIdleMin: 15,
    cutsceneMaxWaitSec: 60,
    sleepSpeedup: 3,
    maxActiveRuns: 3,
    runExpiryDays: 30,
    respawnProtectionSec: 3,
    reviveSeconds: 5,
    medicReviveSeconds: 3,
    secondWindSeconds: 8,
    teamScale: 0.25,
    soloPerkStrength: 0.5,
  },
  scoring: {
    perDay: 100,
    perBoatStage: 500,
    perPlayerRescued: 1000,
    perNpcRescued: 400,
    perCampLevel: 300,
    perGoodAction: 10,
    deathPenalty: 300,
    hazardPenalty: 100,
    sicknessPenalty: 50,
    endingMultiplier: { full_rescue: 1, partial_rescue: 0.6, failed: 0.2 },
  },
  survivors: { min: 3, max: 6 },
  campUpgrades: DEFAULT_CAMP_UPGRADES,
  events: { ...DEFAULT_EVENTS },
  hazards: { ...DEFAULT_HAZARDS },
};
