import type { ItemDef } from './config.ts';

/**
 * Seed item catalog (admin-editable via the Survival config). Every item maps to a real flood
 * lesson where it can. Health/safety lessons are marked for review:
 * VERIFY WITH DOH/MDRRMO before public release (no medicine names or dosages, by design).
 */
const z = {
  camp: 'camp_rooftops',
  res: 'residential',
  market: 'palengke',
  hw: 'hardware',
  health: 'health_center',
  school: 'school',
  church: 'church',
  wires: 'power_lines',
  lake: 'lake_edge',
} as const;

export const DEFAULT_ITEMS: ItemDef[] = [
  // ── Food ────────────────────────────────────────────────────────────
  {
    key: 'canned_goods',
    name: { fil: 'De-lata', en: 'Canned goods' },
    category: 'food',
    weightKg: 0.4,
    stack: 6,
    rarity: 'common',
    zones: [z.res, z.market],
    use: { hunger: 30 },
  },
  {
    key: 'biscuits',
    name: { fil: 'Biskwit', en: 'Biscuits' },
    category: 'food',
    weightKg: 0.2,
    stack: 10,
    rarity: 'common',
    zones: [z.res, z.market, z.school],
    use: { hunger: 15 },
  },
  {
    key: 'instant_noodles',
    name: { fil: 'Instant noodles', en: 'Instant noodles' },
    category: 'food',
    weightKg: 0.1,
    stack: 10,
    rarity: 'common',
    zones: [z.res, z.market],
    use: { hunger: 18 },
  },
  {
    key: 'rice',
    name: { fil: 'Bigas', en: 'Uncooked rice' },
    category: 'food',
    weightKg: 1,
    stack: 5,
    rarity: 'common',
    zones: [z.res, z.market],
  },
  {
    key: 'cooked_rice',
    name: { fil: 'Kanin', en: 'Cooked rice' },
    category: 'food',
    weightKg: 0.5,
    stack: 5,
    rarity: 'common',
    zones: [],
    use: { hunger: 40, learning: 'cooked_food' },
  },
  {
    key: 'raw_fish',
    name: { fil: 'Hilaw na isda', en: 'Raw fish' },
    category: 'food',
    weightKg: 0.5,
    stack: 5,
    rarity: 'common',
    zones: [z.lake],
    use: {
      hunger: 10,
      causes: [{ effect: 'stomach_illness', chance: 0.3 }],
      learning: 'ate_raw_food',
    },
  },
  {
    key: 'cooked_fish',
    name: { fil: 'Lutong isda', en: 'Cooked fish' },
    category: 'food',
    weightKg: 0.4,
    stack: 5,
    rarity: 'common',
    zones: [],
    use: { hunger: 35, learning: 'cooked_food' },
  },
  {
    key: 'coconut',
    name: { fil: 'Buko', en: 'Coconut' },
    category: 'food',
    weightKg: 1.2,
    stack: 3,
    rarity: 'uncommon',
    zones: [z.lake, z.res],
    use: { hunger: 12, thirst: 15 },
  },

  // ── Water ───────────────────────────────────────────────────────────
  {
    key: 'dirty_water',
    name: { fil: 'Maduming tubig', en: 'Dirty floodwater' },
    category: 'water',
    weightKg: 1,
    stack: 3,
    rarity: 'common',
    zones: [z.camp, z.res, z.market, z.lake],
    use: {
      thirst: 15,
      causes: [{ effect: 'stomach_illness', chance: 0.6 }],
      learning: 'drank_unsafe_water',
    },
    // VERIFY WITH DOH/MDRRMO
    lesson: {
      fil: 'Huwag inumin ang tubig-baha. Pakuluan o salain muna.',
      en: 'Never drink floodwater. Boil or filter it first.',
    },
  },
  {
    key: 'rainwater',
    name: { fil: 'Tubig-ulan', en: 'Rainwater' },
    category: 'water',
    weightKg: 1,
    stack: 3,
    rarity: 'common',
    zones: [],
    use: { thirst: 25, causes: [{ effect: 'stomach_illness', chance: 0.15 }] },
  },
  {
    key: 'boiled_water',
    name: { fil: 'Pinakuluang tubig', en: 'Boiled water' },
    category: 'water',
    weightKg: 1,
    stack: 3,
    rarity: 'common',
    zones: [],
    use: { thirst: 35, learning: 'drank_boiled_water' },
    // VERIFY WITH DOH/MDRRMO
    lesson: {
      fil: 'Pakuluan ang tubig nang hindi bababa sa isang minuto bago inumin.',
      en: 'Boil water for at least one minute before drinking.',
    },
  },
  {
    key: 'filtered_water',
    name: { fil: 'Sinalang tubig', en: 'Filtered water' },
    category: 'water',
    weightKg: 1,
    stack: 3,
    rarity: 'common',
    zones: [],
    use: {
      thirst: 30,
      causes: [{ effect: 'stomach_illness', chance: 0.05 }],
      learning: 'used_water_filter',
    },
  },
  {
    key: 'bottled_water',
    name: { fil: 'Bote ng tubig', en: 'Bottled water' },
    category: 'water',
    weightKg: 1,
    stack: 4,
    rarity: 'uncommon',
    zones: [z.res, z.market, z.school, z.health],
    use: { thirst: 40, learning: 'drank_safe_water' },
  },
  {
    key: 'empty_bottle',
    name: { fil: 'Walang lamang bote', en: 'Empty bottle' },
    category: 'material',
    weightKg: 0.1,
    stack: 5,
    rarity: 'common',
    zones: [z.res, z.market, z.camp, z.lake],
  },

  // ── Medical ── VERIFY WITH DOH/MDRRMO (all lessons below) ──────────────
  {
    key: 'bandage',
    name: { fil: 'Benda', en: 'Bandage' },
    category: 'medical',
    weightKg: 0.05,
    stack: 10,
    rarity: 'common',
    zones: [z.health, z.school],
    use: { health: 20, cures: ['open_wound'], learning: 'bandaged_wound' },
    lesson: {
      fil: 'Takpan agad ang sugat bago lumusong sa baha.',
      en: 'Cover wounds before wading through floodwater.',
    },
  },
  {
    key: 'first_aid_kit',
    name: { fil: 'First-aid kit', en: 'First-aid kit' },
    category: 'medical',
    weightKg: 0.6,
    stack: 2,
    rarity: 'uncommon',
    zones: [z.health, z.school, z.church],
    use: { health: 50, cures: ['open_wound'], learning: 'used_first_aid' },
  },
  {
    key: 'medicine',
    name: { fil: 'Gamot mula sa Health Center', en: 'Medicine from the Health Center' },
    category: 'medical',
    weightKg: 0.05,
    stack: 5,
    rarity: 'rare',
    zones: [z.health],
    use: { cures: ['stomach_illness', 'infection'], learning: 'took_medicine' },
    lesson: {
      fil: 'Magpatingin sa doktor kapag nilagnat pagkatapos lumusong sa baha.',
      en: 'See a doctor if you get a fever after wading in floodwater.',
    },
  },
  {
    key: 'alcohol',
    name: { fil: 'Alkohol', en: 'Rubbing alcohol' },
    category: 'medical',
    weightKg: 0.2,
    stack: 3,
    rarity: 'common',
    zones: [z.health, z.res, z.market],
    use: { health: 5, learning: 'cleaned_wound' },
  },
  {
    key: 'clean_cloth',
    name: { fil: 'Malinis na tela', en: 'Clean cloth' },
    category: 'material',
    weightKg: 0.1,
    stack: 10,
    rarity: 'common',
    zones: [z.res, z.health, z.school],
  },

  // ── Clothing ─────────────────────────────────────────────────────────
  {
    key: 'dry_clothes',
    name: { fil: 'Tuyong damit', en: 'Dry clothes' },
    category: 'clothing',
    weightKg: 0.5,
    stack: 3,
    rarity: 'common',
    zones: [z.res, z.market],
    use: { warmth: 40, cures: ['wet', 'hypothermia'], learning: 'changed_dry_clothes' },
    lesson: {
      fil: 'Palitan agad ng tuyong damit para hindi ginawin.',
      en: 'Change into dry clothes right away to avoid hypothermia.',
    },
  },
  {
    key: 'raincoat',
    name: { fil: 'Kapote', en: 'Raincoat' },
    category: 'clothing',
    weightKg: 0.4,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.res, z.market, z.school],
    use: { equip: 'body' },
  },
  {
    key: 'boots',
    name: { fil: 'Bota', en: 'Rubber boots' },
    category: 'clothing',
    weightKg: 1,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.res, z.market, z.hw],
    use: { equip: 'feet', learning: 'wore_boots' },
    // VERIFY WITH DOH/MDRRMO
    lesson: {
      fil: 'Magsuot ng bota at iwasang lumusong sa baha para makaiwas sa leptospirosis.',
      en: 'Wear boots and avoid wading in floodwater to prevent leptospirosis.',
    },
  },
  {
    key: 'blanket',
    name: { fil: 'Kumot', en: 'Blanket' },
    category: 'clothing',
    weightKg: 0.8,
    stack: 2,
    rarity: 'common',
    zones: [z.res, z.church, z.school],
    use: { warmth: 25 },
  },
  {
    key: 'life_vest',
    name: { fil: 'Life vest', en: 'Life vest' },
    category: 'clothing',
    weightKg: 0.7,
    stack: 1,
    rarity: 'rare',
    zones: [z.lake, z.church],
    use: { equip: 'body', learning: 'wore_life_vest' },
  },

  // ── Tools ────────────────────────────────────────────────────────────
  {
    key: 'axe',
    name: { fil: 'Palakol', en: 'Axe' },
    category: 'tool',
    weightKg: 1.5,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.hw],
    durability: 120,
    use: { equip: 'hand' },
    lesson: {
      fil: 'Gumamit ng tamang kagamitan at mag-ingat sa paligid.',
      en: 'Use the right tool and mind the people around you.',
    },
  },
  {
    key: 'flashlight',
    name: { fil: 'Flashlight', en: 'Flashlight' },
    category: 'tool',
    weightKg: 0.3,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.res, z.hw, z.school],
    durability: 300,
    use: { equip: 'hand' },
  },
  {
    key: 'batteries',
    name: { fil: 'Baterya', en: 'Batteries' },
    category: 'tool',
    weightKg: 0.1,
    stack: 8,
    rarity: 'common',
    zones: [z.res, z.hw, z.market],
  },
  {
    key: 'knife',
    name: { fil: 'Kutsilyo', en: 'Knife' },
    category: 'tool',
    weightKg: 0.2,
    stack: 1,
    rarity: 'common',
    zones: [z.res, z.market],
    durability: 200,
  },
  {
    key: 'hammer',
    name: { fil: 'Martilyo', en: 'Hammer' },
    category: 'tool',
    weightKg: 0.8,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.hw],
    durability: 400,
  },
  {
    key: 'fishing_rod',
    name: { fil: 'Pamingwit', en: 'Fishing rod' },
    category: 'tool',
    weightKg: 0.5,
    stack: 1,
    rarity: 'common',
    zones: [],
    durability: 30,
  },
  {
    key: 'cooking_pot',
    name: { fil: 'Kaldero', en: 'Cooking pot' },
    category: 'tool',
    weightKg: 1,
    stack: 1,
    rarity: 'common',
    zones: [z.res, z.market],
  },
  {
    key: 'lighter',
    name: { fil: 'Lighter / posporo', en: 'Lighter / matches' },
    category: 'tool',
    weightKg: 0.05,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.res, z.market, z.church],
    durability: 40,
  },
  {
    key: 'whistle',
    name: { fil: 'Pito', en: 'Whistle' },
    category: 'signal',
    weightKg: 0.02,
    stack: 1,
    rarity: 'common',
    zones: [z.school, z.res, z.church],
  },
  {
    key: 'radio',
    name: { fil: 'Radyo', en: 'Radio' },
    category: 'special',
    weightKg: 0.6,
    stack: 1,
    rarity: 'rare',
    zones: [z.church, z.res],
    use: { learning: 'listened_to_radio' },
    lesson: {
      fil: 'Makinig sa opisyal na abiso ng PAGASA at MDRRMO.',
      en: 'Follow official PAGASA and MDRRMO advisories.',
    },
  },
  {
    key: 'torch',
    name: { fil: 'Sulo', en: 'Torch' },
    category: 'tool',
    weightKg: 0.3,
    stack: 1,
    rarity: 'common',
    zones: [],
    durability: 180,
    use: { equip: 'hand' },
  },
  {
    key: 'water_filter',
    name: { fil: 'Panala ng tubig', en: 'Water filter' },
    category: 'tool',
    weightKg: 0.3,
    stack: 1,
    rarity: 'common',
    zones: [],
    durability: 20,
    // VERIFY WITH DOH/MDRRMO
    lesson: {
      fil: 'Nakakatulong ang pansala, pero mas ligtas pa rin ang pakuluan ang tubig.',
      en: 'A filter helps, but boiling is still safer.',
    },
  },

  // ── Materials ────────────────────────────────────────────────────────
  {
    key: 'wood',
    name: { fil: 'Kahoy', en: 'Wood planks' },
    category: 'material',
    weightKg: 1,
    stack: 20,
    rarity: 'common',
    zones: [z.res, z.hw, z.school, z.camp, z.lake],
  },
  {
    key: 'nails',
    name: { fil: 'Pako', en: 'Nails' },
    category: 'material',
    weightKg: 0.01,
    stack: 100,
    rarity: 'common',
    zones: [z.hw, z.res],
  },
  {
    key: 'rope',
    name: { fil: 'Lubid', en: 'Rope' },
    category: 'material',
    weightKg: 0.4,
    stack: 10,
    rarity: 'common',
    zones: [z.hw, z.market, z.lake],
  },
  {
    key: 'string',
    name: { fil: 'Pisi', en: 'String' },
    category: 'material',
    weightKg: 0.02,
    stack: 10,
    rarity: 'common',
    zones: [z.market, z.res, z.school],
  },
  {
    key: 'plastic_drum',
    name: { fil: 'Plastik na drum', en: 'Plastic drum' },
    category: 'material',
    weightKg: 2,
    stack: 4,
    rarity: 'uncommon',
    zones: [z.market, z.school, z.lake],
  },
  {
    key: 'tarp',
    name: { fil: 'Trapal', en: 'Tarp' },
    category: 'material',
    weightKg: 1.2,
    stack: 4,
    rarity: 'uncommon',
    zones: [z.market, z.hw, z.school],
  },
  {
    key: 'metal_sheet',
    name: { fil: 'Yero', en: 'Metal sheet' },
    category: 'material',
    weightKg: 2.5,
    stack: 4,
    rarity: 'uncommon',
    zones: [z.hw, z.wires],
  },
  {
    key: 'cloth',
    name: { fil: 'Tela', en: 'Cloth' },
    category: 'material',
    weightKg: 0.2,
    stack: 10,
    rarity: 'common',
    zones: [z.res, z.market, z.school],
  },
  {
    key: 'bamboo',
    name: { fil: 'Kawayan', en: 'Bamboo' },
    category: 'material',
    weightKg: 1.5,
    stack: 10,
    rarity: 'common',
    zones: [z.lake, z.res],
  },
  {
    key: 'sand',
    name: { fil: 'Buhangin', en: 'Sand' },
    category: 'material',
    weightKg: 0.5,
    stack: 10,
    rarity: 'common',
    zones: [z.hw, z.school],
  },
  {
    key: 'charcoal',
    name: { fil: 'Uling', en: 'Charcoal' },
    category: 'material',
    weightKg: 0.2,
    stack: 10,
    rarity: 'common',
    zones: [z.market],
  },

  // ── Signal ───────────────────────────────────────────────────────────
  {
    key: 'flare',
    name: { fil: 'Flare', en: 'Flare' },
    category: 'signal',
    weightKg: 0.3,
    stack: 2,
    rarity: 'rare',
    zones: [z.church],
  },
  {
    key: 'mirror',
    name: { fil: 'Salamin', en: 'Mirror' },
    category: 'signal',
    weightKg: 0.3,
    stack: 1,
    rarity: 'uncommon',
    zones: [z.res, z.market],
  },
  {
    key: 'chalk',
    name: { fil: 'Tisa', en: 'Chalk' },
    category: 'signal',
    weightKg: 0.05,
    stack: 10,
    rarity: 'common',
    zones: [z.school],
  },
  {
    key: 'bright_cloth',
    name: { fil: 'Matingkad na tela', en: 'Bright cloth' },
    category: 'signal',
    weightKg: 0.2,
    stack: 5,
    rarity: 'uncommon',
    zones: [z.market, z.church],
  },
  {
    key: 'map_piece',
    name: { fil: 'Piraso ng mapa', en: 'Map piece' },
    category: 'special',
    weightKg: 0.01,
    stack: 5,
    rarity: 'rare',
    zones: [z.school, z.church],
  },
];
