-- ════════════════════════════════════════════════════════════════════
-- Baha Ready 3D · 0007 · Reference content seed
-- DECISION: shipped as a migration (not seed.sql) because `supabase db push` does not run
-- seed.sql on remote projects, and the game cannot function without this reference data.
--
-- ⚠ ALL SAFETY CONTENT BELOW IS PLACEHOLDER — VERIFY WITH MDRRMO/NDRRMC before public release.
--   Tips carry needs_verification = true until an admin marks them verified.
--   Hotlines: only 911 is seeded. Local numbers must be added by an admin after verification.
-- ════════════════════════════════════════════════════════════════════

-- ── Go-bag items ── VERIFY WITH MDRRMO/NDRRMC ──────────────────────────
insert into public.gobag_items
  (key, name_fil, name_en, weight_kg, category, is_essential, points, explanation_fil, explanation_en, model_key, is_published, sort_order)
values
  ('drinking_water', 'Inuming tubig (2 litro)', 'Drinking water (2 liters)', 2.00, 'water', true, 120,
   'Madalas marumi ang tubig sa gripo at baha tuwing bagyo. Magdala ng malinis na inuming tubig.',
   'Tap water and floodwater are often contaminated during storms. Bring clean drinking water.', 'water_bottle', true, 1),
  ('ready_food', 'Pagkaing handa nang kainin', 'Ready-to-eat food', 1.50, 'food', true, 100,
   'Pumili ng pagkaing hindi na kailangang lutuin, tulad ng biskwit at de-lata na may easy-open na takip.',
   'Pick food that needs no cooking, like crackers and easy-open canned goods.', 'food_pack', true, 2),
  ('flashlight', 'Flashlight at extrang baterya', 'Flashlight and spare batteries', 0.40, 'light', true, 100,
   'Karaniwang may brownout tuwing malakas na bagyo. Mas ligtas ang flashlight kaysa kandila.',
   'Power outages are common in strong storms. A flashlight is safer than candles.', 'flashlight', true, 3),
  ('first_aid_kit', 'First-aid kit', 'First-aid kit', 0.60, 'health', true, 100,
   'Para sa maliliit na sugat at galos habang lumilikas o nasa evacuation center.',
   'For small cuts and wounds while evacuating or at the evacuation center.', 'first_aid', true, 4),
  ('maintenance_medicine', 'Maintenance na gamot', 'Maintenance medicine', 0.20, 'health', true, 120,
   'Huwag kalimutan ang gamot ng pamilya (hal. para sa altapresyon o diabetes) para sa ilang araw.',
   'Do not forget family medicines (e.g., for high blood pressure or diabetes) for several days.', 'medicine', true, 5),
  ('whistle', 'Pito', 'Whistle', 0.05, 'communication', true, 60,
   'Mas malayo ang naaabot ng tunog ng pito kaysa sigaw kapag kailangan mo ng saklolo.',
   'A whistle carries farther than your voice when you need rescue.', 'whistle', true, 6),
  ('powerbank', 'Powerbank (naka-charge)', 'Charged powerbank', 0.30, 'communication', true, 80,
   'Para manatiling bukas ang cellphone at makatanggap ng abiso at makatawag ng tulong.',
   'Keeps your phone alive to receive alerts and call for help.', 'powerbank', true, 7),
  ('radio', 'Battery-operated na radyo', 'Battery-operated radio', 0.50, 'communication', true, 80,
   'Makakarinig ka pa rin ng balita at abiso kahit walang kuryente o signal.',
   'You can still hear news and advisories without power or cell signal.', 'radio', true, 8),
  ('documents_pouch', 'Mahahalagang dokumento sa waterproof na lalagyan', 'Important documents in a waterproof pouch', 0.30, 'documents', true, 100,
   'Birth certificate, ID, at titulo — ilagay sa waterproof na lalagyan para hindi mabasa.',
   'Birth certificates, IDs, and land titles — keep them in a waterproof pouch so they stay dry.', 'doc_pouch', true, 9),
  ('clothes', 'Tuyong damit', 'Dry clothes', 1.00, 'clothing', true, 80,
   'Nakakapagpalamig at nakakapagod ang basang damit. Magdala ng pamalit.',
   'Wet clothes make you cold and tired faster. Bring a change of clothes.', 'clothes', true, 10),
  ('hygiene_kit', 'Hygiene kit', 'Hygiene kit', 0.60, 'hygiene', true, 60,
   'Sabon, toothbrush, at alcohol para maiwasan ang sakit sa evacuation center.',
   'Soap, toothbrush, and alcohol help prevent illness at the evacuation center.', 'hygiene', true, 11),
  ('cash_small_bills', 'Pera na maliliit na denominasyon', 'Cash in small bills', 0.10, 'money', true, 60,
   'Maaaring hindi gumana ang ATM at e-wallet kapag walang kuryente o signal.',
   'ATMs and e-wallets may not work without power or signal.', 'cash', true, 12),
  ('walking_stick', 'Tungkod o mahabang patpat', 'Walking stick', 0.40, 'tools', false, 40,
   'Gamitin para tantiyahin ang lalim ng tubig at makita ang bukas na manhole.',
   'Use it to test water depth and find open manholes.', 'stick', true, 13),
  ('pet_carrier', 'Lalagyan ng alaga', 'Pet carrier', 1.00, 'pet', false, 40,
   'Mas ligtas dalhin ang alaga sa carrier para hindi ito maanod o mawala.',
   'A carrier keeps your pet from being swept away or getting lost.', 'pet_carrier', true, 14),
  ('television', 'Telebisyon', 'Television', 8.00, 'non_essential', false, -100,
   'Mabigat at hindi makakatulong sa kaligtasan mo. Iangat na lang ito sa mataas na lugar sa bahay.',
   'Heavy and does not help you survive. Move it to a high place at home instead.', 'tv', true, 20),
  ('gaming_console', 'Gaming console', 'Gaming console', 2.50, 'non_essential', false, -50,
   'Hindi kailangan sa paglikas at nagdadagdag lang ng bigat.',
   'Not needed to evacuate and only adds weight.', 'console', true, 21),
  ('rice_sack', 'Isang sako ng bigas', 'A sack of rice', 10.00, 'non_essential', false, -50,
   'Masyadong mabigat dalhin habang lumilikas. Mas praktikal ang pagkaing handa nang kainin.',
   'Too heavy to carry while evacuating. Ready-to-eat food is more practical.', 'rice_sack', true, 22),
  ('laptop', 'Laptop', 'Laptop', 2.00, 'non_essential', false, -20,
   'Madaling masira sa tubig at mabigat. Unahin ang mga kailangan para mabuhay.',
   'Easily damaged by water and heavy. Prioritize survival items.', 'laptop', true, 23),
  ('candles', 'Mga kandila', 'Candles', 0.40, 'non_essential', false, -30,
   'Maaaring pagmulan ng sunog lalo na sa masikip na evacuation center. Mas ligtas ang flashlight.',
   'Can start fires, especially in crowded evacuation centers. A flashlight is safer.', 'candles', true, 24),
  ('extra_shoes', 'Tatlong pares ng sapatos', 'Three pairs of shoes', 1.50, 'non_essential', false, -10,
   'Isang matibay na pares na suot mo na ay sapat na.',
   'One sturdy pair that you are already wearing is enough.', 'shoes', true, 25);

-- ── Home tasks ── VERIFY WITH MDRRMO/NDRRMC ────────────────────────────
insert into public.home_tasks (key, name_fil, name_en, points, explanation_fil, explanation_en, is_published, sort_order) values
  ('switch_off_breaker', 'Patayin ang main breaker', 'Switch off the main breaker', 150,
   'Pinipigilan nito ang kuryente na dumaloy sa tubig-baha sa loob ng bahay.',
   'This keeps electricity from flowing into floodwater inside the house.', true, 1),
  ('elevate_appliances', 'Iangat ang mga appliance', 'Move appliances to a higher place', 100,
   'Iniiwasan nitong masira ang mga gamit kapag pumasok ang tubig.',
   'This protects your belongings if water gets in.', true, 2),
  ('secure_documents', 'Itabi nang ligtas ang mga dokumento', 'Secure important documents', 100,
   'Ilagay sa waterproof na lalagyan at dalhin sa go-bag.',
   'Put them in a waterproof pouch and bring them in your go-bag.', true, 3),
  ('charge_devices', 'I-charge ang cellphone at powerbank', 'Charge phone and powerbank', 80,
   'Kailangan mo ang cellphone para sa abiso at pagtawag ng tulong.',
   'You need your phone for alerts and to call for help.', true, 4),
  ('bring_pets_inside', 'Ipasok ang mga alaga', 'Bring pets indoors', 80,
   'Huwag iwanang nakatali ang alaga sa labas habang may bagyo.',
   'Never leave pets tied up outside during a storm.', true, 5),
  ('fill_water_containers', 'Punuin ang mga lalagyan ng malinis na tubig', 'Fill containers with clean water', 80,
   'Maaaring mawalan ng suplay ng tubig pagkatapos ng bagyo.',
   'Water supply may be cut off after the storm.', true, 6),
  ('secure_outdoor_items', 'Itali o ipasok ang mga gamit sa labas', 'Secure loose outdoor items', 80,
   'Ang mga yero, paso, at upuan ay maaaring liparin ng hangin at makasakit.',
   'Roof sheets, pots, and chairs can be blown away and hurt people.', true, 7);

-- ── Hazards ── VERIFY WITH MDRRMO/NDRRMC ───────────────────────────────
insert into public.hazards (key, name_fil, name_en, penalty, instant_fail, explanation_fil, explanation_en, is_published) values
  ('live_wire', 'Live na kawad ng kuryente', 'Live electrical wire', 1000, true,
   'Huwag lumapit sa nakalaylay na kawad, lalo na kung nasa tubig ka. Maaaring makuryente kahit hindi mo ito hawakan.',
   'Stay away from fallen wires, especially in water. You can be electrocuted without touching them.', true),
  ('open_manhole', 'Bukas na manhole', 'Open manhole', 300, false,
   'Hindi mo makikita ang manhole sa maputik na baha. Gumamit ng patpat o sundan ang ligtas na daan.',
   'You cannot see manholes in murky floodwater. Use a stick or follow the safe path markers.', true),
  ('debris', 'Mga nakalutang na kalat', 'Floating debris', 100, false,
   'Ang kahoy, yero, at iba pang kalat ay maaaring makasugat. Umiwas at dahan-dahang maglakad.',
   'Wood, metal sheets, and other debris can injure you. Avoid them and walk slowly.', true),
  ('collapsing_structure', 'Gumuguhong istruktura', 'Collapsing structure', 250, false,
   'Lumayo sa mga pader at bahay na may bitak o nakahilig na.',
   'Stay away from walls and houses that are cracked or leaning.', true),
  ('strong_current', 'Malakas na agos', 'Strong current', 150, false,
   'Kahit 15 sentimetrong rumaragasang tubig ay kayang magpatumba ng tao. Humanap ng ibang daan.',
   'Even 15 centimeters of fast-moving water can knock a person down. Find another route.', true),
  ('lightning_exposure', 'Kidlat sa bukas na lugar', 'Lightning in the open', 200, false,
   'Umiwas sa bukas na lugar at matataas na bagay tulad ng poste kapag may kidlat.',
   'Avoid open areas and tall objects like posts during lightning.', true);

-- ── NPC types ── VERIFY WITH MDRRMO/NDRRMC ─────────────────────────────
insert into public.npc_types (key, name_fil, name_en, needs, points, is_published) values
  ('elderly', 'Lolo o Lola', 'Elderly neighbor', '{"speedMultiplier":0.6,"note":"Mas mabagal maglakad"}', 300, true),
  ('child', 'Bata', 'Child', '{"holdHand":true,"speedMultiplier":0.85}', 300, true),
  ('pwd', 'Kapitbahay na PWD', 'Neighbor with a disability', '{"noStairs":true,"speedMultiplier":0.7}', 350, true),
  ('pet', 'Alagang hayop', 'Pet', '{"requiresItem":"pet_carrier"}', 200, true);

-- ── Achievements ───────────────────────────────────────────────────────
insert into public.achievements (key, name_fil, name_en, description_fil, description_en, icon_key, rule, reward_items, sort_order) values
  ('unang_hakbang', 'Unang Hakbang', 'First Step', 'Tapusin ang tutorial.', 'Finish the tutorial.', 'footprints',
   '{"type":"level_complete","level":0}', '{hat_cap_blue}', 1),
  ('handang_handa', 'Handang-handa', 'Fully Prepared', 'Makabuo ng perpektong go-bag sa kahit anong level.', 'Pack a perfect go-bag in any level.', 'backpack',
   '{"type":"perfect_gobag"}', '{acc_backpack_orange}', 2),
  ('bayani_ng_barangay', 'Bayani ng Barangay', 'Barangay Hero', 'Iligtas ang lahat ng kapitbahay sa Signal No. 5.', 'Rescue every neighbor in Signal No. 5.', 'heart-handshake',
   '{"type":"all_npcs","level":5}', '{shirt_rescue_red}', 3),
  ('walang_galos', 'Walang Galos', 'Not a Scratch', 'Tapusin ang isang level nang walang natamaang panganib.', 'Finish a level with zero hazard hits.', 'shield-check',
   '{"type":"no_hazards"}', '{hat_helmet_yellow}', 4),
  ('tuloy_tuloy', 'Tuloy-tuloy', 'On a Roll', '7 araw na sunod-sunod na daily challenge.', 'A 7-day daily challenge streak.', 'flame',
   '{"type":"streak","days":7}', '{acc_badge_flame}', 5),
  ('guro_ng_kaligtasan', 'Guro ng Kaligtasan', 'Safety Master', '3 bituin sa lahat ng level.', '3 stars on every level.', 'graduation-cap',
   '{"type":"all_levels_stars","stars":3}', '{hat_grad_cap}', 6),
  ('liwanag_sa_dilim', 'Liwanag sa Dilim', 'Light in the Dark', 'Tapusin ang Signal No. 4 na may dalang flashlight.', 'Finish Signal No. 4 with the flashlight packed.', 'flashlight',
   '{"type":"level_complete_with_item","level":4,"item":"flashlight"}', '{acc_headlamp}', 7);

-- ── Hotlines ── Only 911 is seeded. Admins add verified local numbers. ─
insert into public.hotlines (agency, number, area, is_verified, is_active, sort_order) values
  ('National Emergency Hotline', '911', 'Pambansa / National', true, true, 1);

-- ── Tips (bilingual) ── VERIFY WITH MDRRMO/NDRRMC ──────────────────────
insert into public.tips (slug, title_fil, title_en, body_fil, body_en, category, unlock_rule, is_published, sort_order) values
  ('alamin-ang-signal', 'Alamin ang ibig sabihin ng bawat Signal', 'Know what each Signal means',
   'Ang Tropical Cyclone Wind Signal (TCWS) ng PAGASA ay mula No. 1 hanggang No. 5. Habang tumataas ang numero, mas malakas ang inaasahang hangin at mas maikli ang oras para maghanda.',
   'PAGASA''s Tropical Cyclone Wind Signals (TCWS) go from No. 1 to No. 5. The higher the number, the stronger the expected winds and the less time you have to prepare.',
   'before', '{"type":"always"}', true, 1),
  ('makinig-sa-abiso', 'Makinig sa opisyal na abiso', 'Listen to official advisories',
   'Sundan ang abiso ng PAGASA, NDRRMC, at ng inyong MDRRMO sa radyo, TV, o opisyal na social media. Iwasan ang hindi beripikadong balita.',
   'Follow advisories from PAGASA, the NDRRMC, and your MDRRMO on radio, TV, or official social media. Avoid unverified news.',
   'before', '{"type":"always"}', true, 2),
  ('ihanda-ang-go-bag', 'Ihanda ang go-bag bago pa ang bagyo', 'Pack your go-bag before the storm',
   'Ihanda ang go-bag ng bawat miyembro ng pamilya at ilagay ito malapit sa pinto. Suriin ito tuwing ilang buwan para palitan ang expired na pagkain at gamot.',
   'Prepare a go-bag for every family member and keep it near the door. Check it every few months to replace expired food and medicine.',
   'gobag', '{"type":"always"}', true, 3),
  ('tubig-sa-go-bag', 'Unahin ang malinis na tubig', 'Put clean water first',
   'Maaaring kontaminado ang tubig pagkatapos ng baha. Magdala ng sapat na malinis na inuming tubig para sa unang araw ng paglikas.',
   'Water may be contaminated after a flood. Bring enough clean drinking water for the first day of evacuation.',
   'gobag', '{"type":"mistake","key":"missing_drinking_water"}', true, 4),
  ('gamot-sa-go-bag', 'Huwag kalimutan ang maintenance na gamot', 'Do not forget maintenance medicine',
   'Magdala ng gamot para sa ilang araw at kopya ng reseta. Maaaring walang botika na bukas pagkatapos ng bagyo.',
   'Bring several days of medicine and a copy of the prescription. Pharmacies may be closed after the storm.',
   'health', '{"type":"mistake","key":"missing_maintenance_medicine"}', true, 5),
  ('flashlight-hindi-kandila', 'Flashlight, hindi kandila', 'Flashlight, not candles',
   'Mas ligtas ang flashlight kaysa kandila. Madaling magsimula ng sunog ang kandila, lalo na sa masikip na lugar.',
   'Flashlights are safer than candles. Candles can easily start fires, especially in crowded places.',
   'gobag', '{"type":"mistake","key":"packed_candles"}', true, 6),
  ('timbang-ng-go-bag', 'Tamang bigat ng go-bag', 'Keep your go-bag light',
   'Dapat kaya mong buhatin at dalhin ang go-bag habang naglalakad sa tubig. Iwan ang mga mabibigat at hindi kailangang gamit.',
   'You should be able to carry your go-bag while walking through water. Leave heavy, unnecessary items behind.',
   'gobag', '{"type":"mistake","key":"overweight_gobag"}', true, 7),
  ('dokumento-waterproof', 'Protektahan ang mga dokumento', 'Protect your documents',
   'Ilagay ang birth certificate, ID, at titulo sa waterproof na lalagyan. Magandang may digital na kopya rin.',
   'Keep birth certificates, IDs, and land titles in a waterproof pouch. Digital copies help too.',
   'home', '{"type":"mistake","key":"missing_documents_pouch"}', true, 8),
  ('patayin-ang-breaker', 'Patayin ang main breaker bago lumikas', 'Switch off the main breaker before leaving',
   'Patayin ang main breaker kung tuyo ang paligid mo. Kung basa na ang sahig o nakatayo ka sa tubig, huwag nang galawin ang breaker.',
   'Switch off the main breaker if you are standing somewhere dry. If the floor is wet or you are in water, do not touch the breaker.',
   'electricity', '{"type":"mistake","key":"skipped_switch_off_breaker"}', true, 9),
  ('iangat-ang-appliance', 'Iangat ang mga appliance', 'Raise your appliances',
   'Ilagay sa mataas na lugar ang mga appliance at mahahalagang gamit bago pumasok ang tubig.',
   'Move appliances and valuables to a higher place before water comes in.',
   'home', '{"type":"always"}', true, 10),
  ('lumikas-nang-maaga', 'Lumikas nang maaga', 'Evacuate early',
   'Kapag pinayuhan ng barangay o MDRRMO na lumikas, sumunod agad. Mas mahirap at delikado ang paglikas kapag mataas na ang tubig at gabi na.',
   'When your barangay or MDRRMO advises evacuation, go right away. Evacuating is harder and riskier once water is high or it is dark.',
   'evacuation', '{"type":"always"}', true, 11),
  ('alamin-ang-evacuation-center', 'Alamin ang pinakamalapit na evacuation center', 'Know your nearest evacuation center',
   'Alamin ang evacuation center ng inyong barangay at ang pinakaligtas na daan papunta roon bago pa dumating ang bagyo.',
   'Find out your barangay''s evacuation center and the safest route there before a storm arrives.',
   'evacuation', '{"type":"level_complete","level":1}', true, 12),
  ('iwasan-ang-live-wire', 'Lumayo sa mga live wire', 'Stay away from live wires',
   'Huwag lumapit sa nakalaylay na kawad ng kuryente o poste, lalo na kung nasa tubig. Iulat agad ito sa barangay o sa electric cooperative.',
   'Stay away from fallen wires and posts, especially in water. Report them to your barangay or electric cooperative right away.',
   'electricity', '{"type":"mistake","key":"live_wire"}', true, 13),
  ('ingat-sa-manhole', 'Mag-ingat sa bukas na manhole', 'Watch out for open manholes',
   'Hindi mo makikita ang manhole o kanal sa maputik na tubig. Gumamit ng patpat para tantiyahin ang daan at sundan ang ligtas na ruta.',
   'You cannot see manholes or canals in murky water. Use a stick to test the ground and follow the safe route.',
   'evacuation', '{"type":"mistake","key":"open_manhole"}', true, 14),
  ('malakas-na-agos', 'Iwasan ang rumaragasang tubig', 'Avoid fast-moving water',
   'Kahit mababaw, kayang magpatumba ng tao ang rumaragasang tubig. Humanap ng ibang daan o maghintay ng tulong.',
   'Even shallow fast-moving water can knock you down. Find another route or wait for help.',
   'evacuation', '{"type":"mistake","key":"strong_current"}', true, 15),
  ('kalat-sa-tubig', 'Dahan-dahan sa tubig na may kalat', 'Move slowly through debris',
   'Maglakad nang dahan-dahan at magsuot ng saradong sapatos. Maaaring may matutulis na bagay sa ilalim ng tubig.',
   'Walk slowly and wear closed shoes. There may be sharp objects under the water.',
   'evacuation', '{"type":"mistake","key":"debris"}', true, 16),
  ('lumayo-sa-sirang-istruktura', 'Lumayo sa sirang istruktura', 'Stay away from damaged structures',
   'Huwag sumilong sa mga pader o bahay na may bitak o nakahilig. Maaari itong gumuho.',
   'Do not shelter near cracked or leaning walls and houses. They may collapse.',
   'during', '{"type":"mistake","key":"collapsing_structure"}', true, 17),
  ('kidlat', 'Kapag may kidlat', 'When there is lightning',
   'Umiwas sa bukas na lugar, poste, at matataas na puno. Huwag humawak sa metal na bakod habang may kidlat.',
   'Avoid open areas, posts, and tall trees. Do not hold metal fences during lightning.',
   'during', '{"type":"mistake","key":"lightning_exposure"}', true, 18),
  ('tulungan-ang-matatanda', 'Tulungan ang matatanda', 'Help elderly neighbors',
   'Mas mabagal kumilos ang matatanda. Samahan sila, dalhin ang kanilang gamot, at huwag silang iwan.',
   'Elderly people move more slowly. Stay with them, bring their medicine, and do not leave them behind.',
   'community', '{"type":"mistake","key":"npc_left_elderly"}', true, 19),
  ('hawakan-ang-bata', 'Hawakan ang kamay ng bata', 'Hold children''s hands',
   'Madaling maanod ang bata sa baha. Hawakan ang kanilang kamay o buhatin sila sa malalim na bahagi.',
   'Children are easily swept away by floodwater. Hold their hands or carry them through deep parts.',
   'community', '{"type":"mistake","key":"npc_left_child"}', true, 20),
  ('pwd-na-ruta', 'Pumili ng rutang madaanan ng PWD', 'Pick a route PWDs can use',
   'Iwasan ang hagdan at makikitid na daan kapag may kasamang PWD o naka-wheelchair.',
   'Avoid stairs and narrow paths when helping a PWD or wheelchair user.',
   'community', '{"type":"mistake","key":"npc_left_pwd"}', true, 21),
  ('isama-ang-alaga', 'Isama ang alaga nang ligtas', 'Bring pets safely',
   'Ilagay ang alaga sa carrier o itali nang maayos. Huwag silang iwanang nakatali sa bahay na babaha.',
   'Put pets in a carrier or on a secure leash. Never leave them tied up in a house that will flood.',
   'community', '{"type":"mistake","key":"npc_left_pet"}', true, 22),
  ('huwag-lumangoy-sa-baha', 'Iwasang lumusong sa baha', 'Avoid wading in floodwater',
   'Maaaring may leptospirosis at iba pang sakit ang tubig-baha. Kung kailangang lumusong, magsuot ng bota at maghugas agad pagkatapos.',
   'Floodwater can carry leptospirosis and other diseases. If you must wade, wear boots and wash right after.',
   'health', '{"type":"level_complete","level":2}', true, 23),
  ('leptospirosis', 'Mag-ingat sa leptospirosis', 'Watch out for leptospirosis',
   'Kung lumusong ka sa baha at nilagnat pagkatapos ng ilang araw, magpatingin agad sa health center.',
   'If you waded through floodwater and get a fever days later, see a health center right away.',
   'after', '{"type":"level_complete","level":3}', true, 24),
  ('bumalik-nang-ligtas', 'Bumalik lamang kapag ligtas na', 'Return only when it is safe',
   'Hintayin ang abiso ng barangay bago umuwi. Suriin ang bahay para sa sira at huwag buksan ang kuryente hangga''t hindi natitiyak na ligtas.',
   'Wait for your barangay''s go-ahead before returning. Check your house for damage and do not turn the power on until it is confirmed safe.',
   'after', '{"type":"level_complete","level":4}', true, 25),
  ('linisin-ang-bahay', 'Linisin nang ligtas ang bahay', 'Clean up safely',
   'Magsuot ng guwantes at bota habang naglilinis. Itapon ang pagkaing nabasa ng baha.',
   'Wear gloves and boots while cleaning. Throw away food that touched floodwater.',
   'after', '{"type":"level_complete","level":5}', true, 26),
  ('family-plan', 'Gumawa ng family emergency plan', 'Make a family emergency plan',
   'Pag-usapan kung saan magkikita, sino ang tatawagan, at sino ang tutulong sa matatanda at bata.',
   'Agree on where to meet, whom to call, and who will help elderly family members and children.',
   'before', '{"type":"always"}', true, 27),
  ('i-charge-ang-cellphone', 'I-charge ang cellphone at powerbank', 'Charge your phone and powerbank',
   'Bago dumating ang bagyo, i-full charge ang cellphone at powerbank para may komunikasyon kahit mag-brownout.',
   'Before the storm arrives, fully charge your phone and powerbank so you can still communicate during outages.',
   'before', '{"type":"mistake","key":"skipped_charge_devices"}', true, 28),
  ('mag-ipon-ng-tubig', 'Mag-ipon ng malinis na tubig', 'Store clean water',
   'Punuin ang mga malinis na lalagyan ng tubig bago ang bagyo dahil maaaring maputol ang suplay.',
   'Fill clean containers with water before the storm because supply may be cut off.',
   'home', '{"type":"mistake","key":"skipped_fill_water_containers"}', true, 29),
  ('itali-ang-gamit-sa-labas', 'Itali ang mga gamit sa labas', 'Secure outdoor items',
   'Ipasok o itali ang mga paso, upuan, at yero para hindi liparin ng malakas na hangin.',
   'Bring in or tie down pots, chairs, and roof sheets so strong winds cannot blow them away.',
   'home', '{"type":"mistake","key":"skipped_secure_outdoor_items"}', true, 30),
  ('pito-para-saklolo', 'Gamitin ang pito para humingi ng saklolo', 'Use a whistle to call for help',
   'Tatlong maiikling pito ang karaniwang hudyat ng paghingi ng tulong.',
   'Three short blasts is a common signal that you need help.',
   'during', '{"type":"mistake","key":"missing_whistle"}', true, 31),
  ('sa-evacuation-center', 'Sa evacuation center', 'At the evacuation center',
   'Magparehistro sa mga opisyal, sundin ang mga patakaran, at panatilihing malinis ang lugar para maiwasan ang sakit.',
   'Register with officials, follow the rules, and keep the area clean to prevent illness.',
   'after', '{"type":"level_complete","level":1}', true, 32),
  ('radyo-kapag-walang-signal', 'Radyo kapag walang signal', 'Radio when there is no signal',
   'Kapag nawalan ng kuryente at signal, ang battery-operated na radyo ang pinakamaaasahang pagkukunan ng balita.',
   'When power and signal are down, a battery-operated radio is the most reliable source of news.',
   'during', '{"type":"mistake","key":"missing_radio"}', true, 33);

-- ── Levels + version 1 configs ── VERIFY WITH MDRRMO/NDRRMC ────────────
insert into public.levels (id, slug, name_fil, name_en, sort_order, is_active) values
  (0, 'tutorial', 'Tutorial', 'Tutorial', 0, true),
  (1, 'signal-1', 'Signal No. 1', 'Signal No. 1', 1, true),
  (2, 'signal-2', 'Signal No. 2', 'Signal No. 2', 2, true),
  (3, 'signal-3', 'Signal No. 3', 'Signal No. 3', 3, true),
  (4, 'signal-4', 'Signal No. 4', 'Signal No. 4', 4, true),
  (5, 'signal-5', 'Signal No. 5', 'Signal No. 5', 5, true);

with essentials as (
  select '["drinking_water","ready_food","flashlight","first_aid_kit","maintenance_medicine","whistle","powerbank","radio","documents_pouch","clothes","hygiene_kit","cash_small_bills"]'::jsonb as e
)
insert into public.level_versions (level_id, version, config, notes)
select v.level_id, 1, v.config, 'Initial seed — VERIFY WITH MDRRMO/NDRRMC'
from essentials, lateral (values
  (0::smallint, jsonb_build_object(
    'signal', 0, 'map', 'house', 'tutorial', true, 'prepTimeSec', null, 'evacTimeSec', 120,
    'minDurationSec', 20, 'weightLimitKg', 10, 'waterRiseSpeed', 0.002, 'rainIntensity', 0.2,
    'currentStrength', 0, 'night', false, 'lightning', false, 'maxSpeed', 6,
    'items', e || '["television","gaming_console"]'::jsonb, 'requiredItems', '[]'::jsonb,
    'homeTasks', '["switch_off_breaker","charge_devices"]'::jsonb,
    'hazards', '[]'::jsonb, 'npcs', '[]'::jsonb,
    'announcements', '[]'::jsonb)),
  (1::smallint, jsonb_build_object(
    'signal', 1, 'map', 'street', 'tutorial', false, 'prepTimeSec', 120, 'evacTimeSec', 150,
    'minDurationSec', 40, 'weightLimitKg', 9, 'waterRiseSpeed', 0.004, 'rainIntensity', 0.35,
    'currentStrength', 0.1, 'night', false, 'lightning', false, 'maxSpeed', 6,
    'items', e || '["television","gaming_console","candles"]'::jsonb, 'requiredItems', '[]'::jsonb,
    'homeTasks', '["switch_off_breaker","elevate_appliances","secure_documents","charge_devices","fill_water_containers"]'::jsonb,
    'hazards', '[{"key":"debris","count":2}]'::jsonb, 'npcs', '["child"]'::jsonb,
    'announcements', '[{"atSec":45,"fil":"Nakataas ang Signal No. 1 sa Laguna. Maghanda.","en":"Signal No. 1 is raised over Laguna. Get ready."}]'::jsonb)),
  (2::smallint, jsonb_build_object(
    'signal', 2, 'map', 'plaza', 'tutorial', false, 'prepTimeSec', 100, 'evacTimeSec', 150,
    'minDurationSec', 40, 'weightLimitKg', 9, 'waterRiseSpeed', 0.006, 'rainIntensity', 0.5,
    'currentStrength', 0.25, 'night', false, 'lightning', false, 'maxSpeed', 6,
    'items', e || '["television","gaming_console","candles","rice_sack","walking_stick"]'::jsonb, 'requiredItems', '[]'::jsonb,
    'homeTasks', '["switch_off_breaker","elevate_appliances","secure_documents","charge_devices","fill_water_containers","secure_outdoor_items"]'::jsonb,
    'hazards', '[{"key":"debris","count":4},{"key":"strong_current","count":1}]'::jsonb, 'npcs', '["child","elderly"]'::jsonb,
    'announcements', '[{"atSec":40,"fil":"Itinaas na ang Signal No. 2. Maghanda sa paglikas.","en":"Signal No. 2 is now raised. Prepare to evacuate."}]'::jsonb)),
  (3::smallint, jsonb_build_object(
    'signal', 3, 'map', 'palengke', 'tutorial', false, 'prepTimeSec', 90, 'evacTimeSec', 140,
    'minDurationSec', 35, 'weightLimitKg', 9, 'waterRiseSpeed', 0.008, 'rainIntensity', 0.65,
    'currentStrength', 0.4, 'night', false, 'lightning', false, 'maxSpeed', 6,
    'items', e || '["television","gaming_console","candles","rice_sack","laptop","walking_stick"]'::jsonb, 'requiredItems', '[]'::jsonb,
    'homeTasks', '["switch_off_breaker","elevate_appliances","secure_documents","charge_devices","fill_water_containers","secure_outdoor_items"]'::jsonb,
    'hazards', '[{"key":"live_wire","count":2},{"key":"open_manhole","count":2},{"key":"debris","count":4}]'::jsonb,
    'npcs', '["child","elderly","pwd"]'::jsonb,
    'announcements', '[{"atSec":30,"fil":"Itinaas na ang Signal No. 3. Lumikas na ang mga nasa mababang lugar.","en":"Signal No. 3 is now raised. Residents of low-lying areas must evacuate."}]'::jsonb)),
  (4::smallint, jsonb_build_object(
    'signal', 4, 'map', 'night_town', 'tutorial', false, 'prepTimeSec', 80, 'evacTimeSec', 130,
    'minDurationSec', 30, 'weightLimitKg', 9.5, 'waterRiseSpeed', 0.010, 'rainIntensity', 0.75,
    'currentStrength', 0.5, 'night', true, 'lightning', false, 'maxSpeed', 6,
    'items', e || '["television","gaming_console","candles","laptop","extra_shoes","walking_stick","pet_carrier"]'::jsonb,
    'requiredItems', '["flashlight"]'::jsonb,
    'homeTasks', '["switch_off_breaker","elevate_appliances","secure_documents","charge_devices","bring_pets_inside","fill_water_containers"]'::jsonb,
    'hazards', '[{"key":"live_wire","count":2},{"key":"open_manhole","count":3},{"key":"debris","count":5}]'::jsonb,
    'npcs', '["elderly","child","pet"]'::jsonb,
    'announcements', '[{"atSec":25,"fil":"Brownout sa buong bayan. Itinaas na ang Signal No. 4.","en":"Town-wide brownout. Signal No. 4 is now raised."}]'::jsonb)),
  (5::smallint, jsonb_build_object(
    'signal', 5, 'map', 'town', 'tutorial', false, 'prepTimeSec', 70, 'evacTimeSec', 120,
    'minDurationSec', 30, 'weightLimitKg', 9.5, 'waterRiseSpeed', 0.013, 'rainIntensity', 1.0,
    'currentStrength', 0.8, 'night', false, 'lightning', true, 'maxSpeed', 6,
    'items', e || '["television","gaming_console","candles","rice_sack","laptop","extra_shoes","walking_stick","pet_carrier"]'::jsonb,
    'requiredItems', '[]'::jsonb,
    'homeTasks', '["switch_off_breaker","elevate_appliances","secure_documents","charge_devices","bring_pets_inside","fill_water_containers","secure_outdoor_items"]'::jsonb,
    'hazards', '[{"key":"live_wire","count":3},{"key":"open_manhole","count":3},{"key":"debris","count":6},{"key":"collapsing_structure","count":2},{"key":"strong_current","count":3},{"key":"lightning_exposure","count":1}]'::jsonb,
    'npcs', '["elderly","child","pwd","pet","elderly"]'::jsonb,
    'announcements', '[{"atSec":20,"fil":"Itinaas na ang Signal No. 5! Lumikas agad.","en":"Signal No. 5 is now raised! Evacuate immediately."}]'::jsonb))
) as v(level_id, config);

update public.levels l set current_version_id = lv.id
from public.level_versions lv where lv.level_id = l.id and lv.version = 1;

-- Today's daily challenge so the feature works immediately.
select public.generate_daily_challenge();
